### ISSUE TITLE
Incompatible with Gnembon's Carpet mod. 

### ISSUE THREAD

**Issue by QPCrummer** [BukkitFabric/bukkit4fabric#12]
Time: 8/30/20 3:08 PM
Description: Exception in server tick loop

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.class_3176.handler$zzd000$init(class_3176.java:675)
	at net.minecraft.class_3176.method_3823(class_3176.java:150)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [carpet.mixins.json:ServerPlayerInteractionManager_cactusMixin] from phase [DEFAULT] in config [carpet.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3225::activateWithOptionalCactus with priority 1000 cannot inject into net/minecraft/class_3225::method_14262(Lnet/minecraft/class_3222;Lnet/minecraft/class_1937;Lnet/minecraft/class_1799;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_1269; merged by com.javazilla.bukkitfabric.mixin.MixinServerPlayerInteractionManager with priority 1000 [PREINJECT Applicator Phase -> carpet.mixins.json:ServerPlayerInteractionManager_cactusMixin -> Prepare Injections ->  -> redirect$zob000$activateWithOptionalCactus(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_1269; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Linux (amd64) version 3.10.0-1062.12.1.el7.x86_64
	Java Version: 1.8.0_252, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8051132112 bytes (7678 MB) / 8476557312 bytes (8083 MB) up to 8476557312 bytes (8083 MB)
	CPUs: 16
	JVM Flags: 4 total; -Xmx8192M -Xms8192M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled
	Fabric Mods: 
		bukkitfabric: Bukkit for Fabric 1.16.2
		carpet: Carpet Mod in Fabric 1.4.8
		carpet-extra: Carpet Extra 1.4.8
		carpet-tis-addition: Carpet TIS Addition 1.0.13
		dupeplayerjoin: Duplicate Player Join ${version}
		fabric: Fabric API 0.19.0+build.398-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c4e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.0+516ece7c4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.9.2+build.206
		lithium: Lithium 0.5.2
		minecraft: Minecraft 1.16.2
	Data Packs: vanilla, file/wipeout map creator, file/bukkit, file/Happy.zip (incompatible), file/Megalovania.zip (incompatible), file/Munkee.zip (incompatible), file/Problem.zip (incompatible), file/Up.zip (incompatible), file/bedwars_gui - A GUI Datapack Generated by objD.zip (incompatible), fabric/fabric-tool-attribute-api-v1
	Is Modded: Definitely; Server brand changed to 'Fabric,Bukkit'
	Type: Dedicated Server (map_server.txt)

**Comment by ZachTheDev** [comment]
@IsaiahPatton I am having this issue aswell. I tried setting the priority of all the files to 999, like you had done on commit 018f81e. But then the issue turned into this: `org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Conflicting type cast at offset 4 in synthetic bridge method method_16901(Ljava/lang/Object;)V`
I am just divining into this with no idea what I am doing. 
Are you planning on working on this?

**Comment by QPCrummer** [comment]
Yeah, it was fixed, then got reintroduced into the mod sadly.

**Comment by QPCrummer** [comment]
Server thread/FATAL Mixin apply failed carpet.mixins.json:ServerPlayNetworkHandler_interactionUpdatesMixin -> net.minecraft.class_3244: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_3244::beforeItemInteracted with priority 1000 cannot inject into net/minecraft/class_3244::method_12065(Lnet/minecraft/class_2886;)V merged by com.javazilla.bukkitfabric.mixin.network.MixinServerPlayNetworkHandler with priority 1000 [PREINJECT Applicator Phase -> carpet.mixins.json:ServerPlayNetworkHandler_interactionUpdatesMixin -> Prepare Injections ->  -> handler$zok000$beforeItemInteracted(Lnet/minecraft/class_2886;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
14.10 13:00:49 [Server] INFO org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_3244::beforeItemInteracted with priority 1000 cannot inject into net/minecraft/class_3244::method_12065(Lnet/minecraft/class_2886;)V merged by com.javazilla.bukkitfabric.mixin.network.MixinServerPlayNetworkHandler with priority 1000 [PREINJECT Applicator Phase -> carpet.mixins.json:ServerPlayNetworkHandler_interactionUpdatesMixin -> Prepare Injections ->  -> handler$zok000$beforeItemInteracted(Lnet/minecraft/class_2886;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
14.10 13:00:49 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148) ~[fabric_1.16.3.jar:?]
14.10 13:00:49 [Multicraft] Server shut down (starting)
14.10 13:00:49 [Multicraft] Restarting crashed server in 300 seconds
14.10 13:00:49 [Multicraft] Server stopped
14.10 13:00:55 [Multicraft] Received stop command
14.10 13:00:55 [Multicraft] Server stopped

**Comment by cuajil** [comment]
I'm able to run Gnembon's Carpet Mod along with bukkit4fabric. Tested tickwarp and scripts and found no problems. It crashed when I tried to load the Fabric-API though, so you can't use accurate block placement. I have lithium and phosphor running along with it, but nothing else.

**Comment by QPCrummer** [comment]
It is the auto crafting table addon for it. Look at my latest issue post.

**Comment by danteali** [comment]
I think we should revert title back to incompatible with Carpet Mod.
Server crashes on startup with only Fabric API (0.34.6), Carpet Mod (1.4.40+v210608) and Cardboard (#162) loaded,
```

[23:23:24] [main/FATAL]: Mixin apply failed carpet.mixins.json:MinecraftServer_tickspeedMixin -> net.minecraft.server.MinecraftServer: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Conflicting type cast at offset 4 in synthetic bridge method method_16901(Ljava/lang/Object;)V
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Conflicting type cast at offset 4 in synthetic bridge method method_16901(Ljava/lang/Object;)V
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachUniqueMethod(MixinPreProcessorStandard.java:551) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:338) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
        at net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents.lambda$static$1(S2CPlayChannelEvents.java:36) ~[97a5aec2-e5cb-426a-9c92-28a6432c2d70.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:41) ~[a48eb0b1-1dc0-44c4-8be5-dcefb740c1e6.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:37) ~[a48eb0b1-1dc0-44c4-8be5-dcefb740c1e6.jar:?]
        at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:42) ~[a48eb0b1-1dc0-44c4-8be5-dcefb740c1e6.jar:?]
        at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:61) ~[a48eb0b1-1dc0-44c4-8be5-dcefb740c1e6.jar:?]
        at net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents.<clinit>(S2CPlayChannelEvents.java:36) ~[97a5aec2-e5cb-426a-9c92-28a6432c2d70.jar:?]
        at net.fabricmc.fabric.impl.networking.OldNetworkingHooks.onInitialize(OldNetworkingHooks.java:27) ~[fe9a85dd-b9c4-4a46-b9a0-c1ea432fdcc5.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) [fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]

```
