### ISSUE TITLE
mcMMO plugin compatibility

### ISSUE THREAD

**Issue by Ryacrock** [BukkitFabric/bukkit4fabric#15]
I know you said that you have to add some things for this to work already. Just posting up a reference as of build #71. This is with no other mods besides Bukkit4Fabric and no other plugins besides mcMMO Overhaul.

[21:05:41 INFO]: Copyright © 2020
[21:05:42 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[21:05:43 WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:05:43 WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:05:43 WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:05:43 WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:05:43 WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:05:43 INFO]: Reloading ResourceManager: Default, Fabric Tool Attribute API (v1)
[21:05:43 INFO]: Loaded 7 recipes
[21:05:43 INFO]: Loaded 927 advancements
[21:05:44 INFO]: Starting minecraft server version 1.16.2
[21:05:44 INFO]: Loading properties
[21:05:44 INFO]: Default game type: SURVIVAL
[21:05:44 INFO]: Generating keypair
[21:05:45 INFO]: Starting Minecraft server on *:25565
[21:05:45 INFO]: Using default channel type
[21:05:45 INFO]:   ____          _     _     _  _    
[21:05:45 INFO]:  |  _ \        | |   | |   (_)| |   
[21:05:45 INFO]:  | |_) | _   _ | | __| | __ _ | |_  
[21:05:45 INFO]:  |  _ < | | | || |/ /| |/ /| || __| 
[21:05:45 INFO]:  | |_) || |_| ||   < |   < | || |_  
[21:05:45 INFO]:  |____/  \__,_||_|\_\|_|\_\|_| \__| 
[21:05:45 INFO]: 
[21:05:46 INFO]: This server is running Bukkit4Fabric version git-Bukkit4Fabric-UNKNOWN (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[21:05:46 INFO]: Loading Bukkit plugins...
[21:05:46 INFO]: 
[21:05:46 INFO]: Preparing level "world"
[21:05:46 WARN]: Unable to find spawn biome
[21:05:46 WARN]: Unable to find spawn biome
[21:05:46 INFO]: Preparing start region for dimension minecraft:overworld
[21:05:47 INFO]: Preparing spawn area: 0%
[21:05:47 INFO]: Preparing spawn area: 0%
[21:05:47 INFO]: Time elapsed: 869 ms
[21:05:47 INFO]: Preparing start region for dimension minecraft:the_nether
[21:05:47 INFO]: Preparing spawn area: 0%
[21:05:48 INFO]: Preparing spawn area: 83%
[21:05:48 INFO]: Preparing spawn area: 83%
[21:05:49 INFO]: Preparing spawn area: 83%
[21:05:49 INFO]: Preparing spawn area: 89%
[21:05:50 INFO]: Preparing spawn area: 95%
[21:05:50 INFO]: Time elapsed: 2738 ms
[21:05:50 INFO]: Preparing start region for dimension minecraft:the_end
[21:05:50 INFO]: Preparing spawn area: 0%
[21:05:51 INFO]: Preparing spawn area: 83%
[21:05:51 INFO]: Time elapsed: 869 ms
[21:05:51 INFO]: [STDERR]: java.lang.ClassCastException: org.bukkit.craftbukkit.inventory.CraftMetaMap cannot be cast to org.bukkit.inventory.meta.PotionMeta
[21:05:51 INFO]: [STDERR]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadTreasures(TreasureConfig.java:204)
[21:05:51 INFO]: [STDERR]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:99)
[21:05:51 INFO]: [STDERR]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:37)
[21:05:51 INFO]: [STDERR]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:43)
[21:05:51 INFO]: [STDERR]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:501)
[21:05:51 INFO]: [STDERR]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:168)
[21:05:51 INFO]: [STDERR]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:05:51 INFO]: [STDERR]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[21:05:51 INFO]: [STDERR]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[21:05:51 INFO]: [STDERR]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:377)
[21:05:51 INFO]: [STDERR]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:311)
[21:05:51 INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:1983)
[21:05:51 INFO]: [STDERR]: 	at net.minecraft.class_3176.method_3823(class_3176.java:174)
[21:05:51 INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642)
[21:05:51 INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
[21:05:51 INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[21:05:52 INFO]: [STDERR]: java.lang.NullPointerException
[21:05:52 INFO]: [STDERR]: 	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:318)
[21:05:52 INFO]: [STDERR]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[21:05:52 INFO]: [STDERR]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376)
[21:05:52 INFO]: [STDERR]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501)
[21:05:52 INFO]: [STDERR]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:262)
[21:05:52 INFO]: [STDERR]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:05:52 INFO]: [STDERR]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[21:05:52 INFO]: [STDERR]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[21:05:52 INFO]: [STDERR]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:377)
[21:05:52 INFO]: [STDERR]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:311)
[21:05:52 INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:1983)
[21:05:52 INFO]: [STDERR]: 	at net.minecraft.class_3176.method_3823(class_3176.java:174)
[21:05:52 INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642)
[21:05:52 INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
[21:05:52 INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[21:05:52 FATAL]: Error occurred while disabling mcMMO v2.1.145 (Is it up to date?)
java.lang.NullPointerException: null
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:350) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Bukkit4Fabric-1.16.2.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) ~[Bukkit4Fabric-1.16.2.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[Bukkit4Fabric-1.16.2.jar:?]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:262) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Bukkit4Fabric-1.16.2.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[Bukkit4Fabric-1.16.2.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[Bukkit4Fabric-1.16.2.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:377) ~[Bukkit4Fabric-1.16.2.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:311) ~[Bukkit4Fabric-1.16.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:1983) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:174) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[21:05:52 WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:05:52 WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:05:52 WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:05:52 WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:05:52 WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:05:52 INFO]: Done (5.457s)! For help, type "help"

**Comment by IsaiahPatton** [comment]
Fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/beb1404e38462a7edcf6d76f563bce92e337b24e .
mcMMO now works.
