### ISSUE TITLE
Dynamap not working?

### ISSUE THREAD

**Issue by kni0002** [BukkitFabric/bukkit4fabric#16]
Seems like when i try to use the /dynamap command i get an unexpected error
![image](https://user-images.githubusercontent.com/20548684/91928193-c352b280-ed1e-11ea-95b4-3c1367c10456.png)

**Comment by MiniDay** [comment]
If I'm right, dynmap does not currently support bukkit 1.16.3  

Even bukkit / spigot servers without fabric cannot be used.   

A few days ago, I tested several versions of dynmap and found that none of them could be used on bukkit.

**Comment by xenoflot** [comment]
Dynmap works fine under 1.16.3 with the current version. I've got it working both with the Fabric and Spigot versions.

Sadly, I've not had any success getting it working with Bukkit4Fabric. The plugin version is not compatible with the current version of Bukkit4Fabric, and the mod version causes a crash on boot. Remove either Bukkit4Fabric or DynMap and the server boots normally.

Crash (mod ver) log: https://pastebin.com/75ZZNRTE
Bukkit4Fabric-1.16.3
Dynmap-3.1-beta4-fabric-1.16.2
fabric-api-0.24.0+build.411-1.16
Plugin folder is empty. 

Plugin log: 
[12:30:40] [Server thread/FATAL]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.1-beta4-421 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:166) ~[?:?]
	at org.dynmap.bukkit.helper.v116_3.BukkitVersionHelperSpigot116_3.<init>(BukkitVersionHelperSpigot116_3.java:46) ~[?:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:46) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:821) ~[?:?]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:356) ~[Bukkit4Fabric-1.16.3.jar:?]
	at net.minecraft.class_3176.handler$zze000$init(class_3176.java:711) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:150) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
