### ISSUE TITLE
Core Protect Partial Functionality

### ISSUE THREAD

**Issue by Gryzle** [BukkitFabric/bukkit4fabric#17]
When using the plugin [Core Protect](https://www.spigotmc.org/resources/coreprotect.8631/), you can see data on blocks, buttons, doors, etc. but not with containers such as hoppers, chests, and barrels. When trying to inspect a chest, it simply opens the chest. If you place a block on top of the chest and try again, it doesn't open the chest, but it also doesn't do anything. Barrels say "No Transaction" even after items have been removed or added to it, hoppers are the same.

Thanks in advance!

**Comment by TheNukeLore** [comment]
is this issue going to be fixed? because i have a server that needs bukkit plugins but it almost needs lithium or else it cant run

**Comment by Kowagatte** [comment]
Expanding on this issue, in build 120 with no other mods, and only core protect on a fresh server. Block histories work, but upon left clicking on any Container BlockEntity I get the error:
````
[12:09:59] [Server thread/FATAL]: Error executing task on Server
net.minecraft.class_148: Sending packet
        at net.minecraft.class_3244.method_14369(class_3244.java:1081) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_14364(class_3244.java:1057) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14263(class_3225.java:617) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12066(class_3244.java:940) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_12361(class_2846.java:40) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_11054(class_2846.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:758) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:152) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:740) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:734) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:103) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:718) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.lang.NullPointerException
        at net.minecraft.class_2539.method_10786(class_2539.java:463) ~[intermediary-server.jar:?]
        at net.minecraft.class_2535.method_10764(class_2535.java:180) ~[intermediary-server.jar:?]
        at net.minecraft.class_2535.method_10752(class_2535.java:173) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_14369(class_3244.java:1074) ~[intermediary-server.jar:?]
        ... 19 more

```
