### ISSUE TITLE
QuickShop compatibility: ClassCastException: net.minecraft.class_3218 cannot be cast to org.bukkit.World

### ISSUE THREAD

**Issue by Ghost-chu** [BukkitFabric/bukkit4fabric#21]
```
[17:54:32] [Server thread/FATAL]: Could not pass event PlayerInteractEvent to QuickShop v4.0.4.10
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[Bukkit4Fabric-1.16.3.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Bukkit4Fabric-1.16.3.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[Bukkit4Fabric-1.16.3.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[Bukkit4Fabric-1.16.3.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:138) ~[Bukkit4Fabric-1.16.3.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:106) ~[Bukkit4Fabric-1.16.3.jar:?]
        at net.minecraft.class_3225.method_14263(class_3225.java:609) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12066(class_3244.java:940) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_12361(class_2846.java:40) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_11054(class_2846.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:758) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:152) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:740) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:734) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:719) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.ClassCastException: net.minecraft.class_3218 cannot be cast to org.bukkit.World
        at org.bukkit.craftbukkit.CraftChunk.getWorld(CraftChunk.java:62) ~[Bukkit4Fabric-1.16.3.jar:?]
        at org.maxgamer.quickshop.shop.ShopManager.getShops(ShopManager.java:170) ~[?:?]
        at org.maxgamer.quickshop.shop.ShopManager.getShop(ShopManager.java:286) ~[?:?]
        at org.maxgamer.quickshop.shop.ShopManager.getShop(ShopManager.java:272) ~[?:?]
        at org.maxgamer.quickshop.listener.PlayerListener.onClick(PlayerListener.java:96) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[Bukkit4Fabric-1.16.3.jar:?]
        ... 23 more
```

**Comment by IsaiahPatton** [comment]
fixed
