### ISSUE TITLE
Incompatible with LockettePro and Graves Plugin

### ISSUE THREAD

**Issue by Garry63566** [BukkitFabric/bukkit4fabric#262]

**Comment by Garry63566** [comment]
For graves plugin: 
[17:06:09] [Server thread/FATAL]: Could not pass event PlayerDeathEvent to Graves v3.8
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.setInvulnerable(boolean)" because "armorStand" is null
        at com.ranull.graves.manager.GraveManager.createHologram(GraveManager.java:1229) ~[?:?]
        at com.ranull.graves.manager.GraveManager.placeGrave(GraveManager.java:603) ~[?:?]
        at com.ranull.graves.manager.GraveManager.createGrave(GraveManager.java:449) ~[?:?]
        at com.ranull.graves.listeners.Events.onPlayerDeath(Events.java:123) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor23.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.17-dev.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.17-dev.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.17-dev.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[paper-api-1.17-dev.jar:?]
        at com.javazilla.bukkitfabric.impl.BukkitEventFactory.callPlayerDeathEvent(BukkitEventFactory.java:530) ~[CardboardMod-1.17.jar:?]
        at net.minecraft.class_3222.handler$zbe000$bukkitizeDeath(class_3222.java:1947) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_6078(class_3222.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_5643(class_1309.java:1177) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_5643(class_1657.java:914) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_5643(class_3222.java:664) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_5747(class_1309.java:1519) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_5747(class_1657.java:1699) ~[intermediary-server.jar:?]
        at net.minecraft.class_2248.method_9554(class_2248.java:464) ~[intermediary-server.jar:?]
        at net.minecraft.class_1297.method_5623(class_1297.java:1153) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_5623(class_1309.java:318) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_14207(class_3222.java:969) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.handler$zcp000$onPlayerMove_Cardboard(class_3244.java:2082) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12063(class_3244.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_2828.method_12272(class_2828.java:114) ~[intermediary-server.jar:?]
        at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:42) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Garry63566** [comment]
For Lockettepro, no signs on command on console when when using a sign to right-click a chest the chest is also not locked
