### ISSUE TITLE
lost connection: Invalid player data when using cardboard

### ISSUE THREAD

**Issue by twilightsg** [BukkitFabric/bukkit4fabric#263]
Server setup
1.17.1 Fabric

update
Now I kwon the mod bewitchment is the reason this problem.

I always got Lost connection when I use Cardboard
I didn't use any plugins
Without Cardboard the server run find and every mods work.
I can sign in server correct,
After I install Cardboard 1.17 35 

I cannot sign in the game and I think it should be some problem with Origin and Cardboard

> [14:04:23] [User Authenticator #0/INFO]: UUID of player Twilight_SG is 49ce3ddf-672d-4a3c-abe1-8c0c7a9a1748
> [14:04:23] [Server thread/INFO]: Twilight_SG[/127.0.0.1:61775] logged in with entity id 404 at (202.5, 67.0, 194.5)
> [14:04:23] [Server thread/WARN]: Player class_3222['Twilight_SG'/404, l='ServerLevel[world]', x=202.50, y=67.00, z=194.50] could not be synced because server networking isn't set up yet.
> [14:04:23] [Server thread/INFO]: Twilight_SG lost connection: Invalid player data
> [14:04:23] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:61775
> java.lang.ClassCastException: class net.minecraft.class_2588 cannot be cast to class io.github.ladysnake.impersonate.impl.RecipientAwareText (net.minecraft.class_2588 and io.github.ladysnake.impersonate.impl.RecipientAwareText are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @14028087)
>         at net.minecraft.server.MinecraftServer.localvar$zmi000$revealImpersonatorsInMessages(MinecraftServer.java:3796) ~[intermediary-server.jar:?]
>         at net.minecraft.server.MinecraftServer.method_9203(MinecraftServer.java) ~[intermediary-server.jar:?]
>         at net.minecraft.class_3324.method_14616(class_3324.java:766) ~[intermediary-server.jar:?]
>         at net.minecraft.class_3244.method_10839(class_3244.java:1133) ~[intermediary-server.jar:?]
>         at net.minecraft.class_2535.method_10768(class_2535.java:413) ~[intermediary-server.jar:?]
>         at net.minecraft.class_2535.method_10754(class_2535.java:242) ~[intermediary-server.jar:?]
>         at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-server.jar:?]
>         at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902) ~[intermediary-server.jar:?]
>         at net.minecraft.class_3176.method_3813(class_3176.java:335) ~[intermediary-server.jar:?]
>         at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-server.jar:?]
>         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[intermediary-server.jar:?]
>         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
>         at java.lang.Thread.run(Unknown Source) [?:?]
> [14:04:23] [Server thread/WARN]: handleDisconnection() called twice
> [14:10:21] [User Authenticator #0/INFO]: UUID of player Twilight_SG is 49ce3ddf-672d-4a3c-abe1-8c0c7a9a1748
> [14:10:21] [Server thread/INFO]: Twilight_SG[/127.0.0.1:52216] logged in with entity id 405 at (204.5, 67.0, 194.5)
> [14:10:21] [Server thread/WARN]: Player class_3222['Twilight_SG'/405, l='ServerLevel[world]', x=204.50, y=67.00, z=194.50] could not be synced because server networking isn't set up yet.
> [14:10:21] [Server thread/INFO]: Twilight_SG lost connection: Invalid player data
> [14:10:21] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:52216
> java.lang.ClassCastException: class net.minecraft.class_2588 cannot be cast to class io.github.ladysnake.impersonate.impl.RecipientAwareText (net.minecraft.class_2588 and io.github.ladysnake.impersonate.impl.RecipientAwareText are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @14028087)
>         at net.minecraft.server.MinecraftServer.localvar$zmi000$revealImpersonatorsInMessages(MinecraftServer.java:3796) ~[intermediary-server.jar:?]
>         at net.minecraft.server.MinecraftServer.method_9203(MinecraftServer.java) ~[intermediary-server.jar:?]
>         at net.minecraft.class_3324.method_14616(class_3324.java:766) ~[intermediary-server.jar:?]
>         at net.minecraft.class_3244.method_10839(class_3244.java:1133) ~[intermediary-server.jar:?]
>         at net.minecraft.class_2535.method_10768(class_2535.java:413) ~[intermediary-server.jar:?]
>         at net.minecraft.class_2535.method_10754(class_2535.java:242) ~[intermediary-server.jar:?]
>         at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-server.jar:?]
>         at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902) ~[intermediary-server.jar:?]
>         at net.minecraft.class_3176.method_3813(class_3176.java:335) ~[intermediary-server.jar:?]
>         at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-server.jar:?]
>         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[intermediary-server.jar:?]
>         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
>         at java.lang.Thread.run(Unknown Source) [?:?]
> [14:10:21] [Server thread/WARN]: handleDisconnection() called twice

This is what happen when I use Origin1.0.3 and Cardboard.
And now I still want try Cardboard

But when I remove origin and origin-classic Still got this problem
So I remove all of the mods and finally it works

now I am looking for which one mod lead this problem

This is mods I installed
[modslist.txt](https://github.com/CardboardPowered/cardboard/files/7167496/modslist.txt)

Not sure if I do right.

**Comment by itsdinkd** [comment]
io.github.ladysnake.impersonate.impl.RecipientAwareText (net.minecraft.class_2588 and io.github.ladysnake.impersonate.impl.RecipientAwareText are in unnamed module of loader 


The problem is impersonate, not bewitchment

**Comment by twilightsg** [comment]
> io.github.ladysnake.impersonate.impl.RecipientAwareText (net.minecraft.class_2588 and io.github.ladysnake.impersonate.impl.RecipientAwareText are in unnamed module of loader
> 
> The problem is impersonate, not bewitchment

Sorry but I'm not very clear what should I do, can you give me some kinds of guide?
