### ISSUE TITLE
Mysterious crash

### ISSUE THREAD

**Issue by ry0shi** [BukkitFabric/bukkit4fabric#271]
```
[19:43:03] [main/FATAL]: Mixin apply failed mixins.simpleauth.json:MixinWorldSaveHandler -> net.minecraft.class_29: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_29::fileExists with priority 1000 cannot inject into net/minecraft/class_29::method_261(Lnet/minecraft/class_1657;)Lnet/minecraft/class_2487; merged by org.cardboardpowered.mixin.world.MixinWorldSaveHandler with priority 1000 [PREINJECT Applicator Phase -> mixins.simpleauth.json:MixinWorldSaveHandler -> Prepare Injections -> -> handler$zhh000$fileExists(Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2487;Ljava/io/File;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_29::fileExists with priority 1000 cannot inject into net/minecraft/class_29::method_261(Lnet/minecraft/class_1657;)Lnet/minecraft/class_2487; merged by org.cardboardpowered.mixin.world.MixinWorldSaveHandler with priority 1000 [PREINJECT Applicator Phase -> mixins.simpleauth.json:MixinWorldSaveHandler -> Prepare Injections -> -> handler$zhh000$fileExists(Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2487;Ljava/io/File;)V -> Prepare]
at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-server-launch.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
at net.minecraft.class_32$class_5143.method_27427(class_32.java:310) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:279) ~[intermediary-server.jar:?]
at net.minecraft.class_3176.<init>(class_3176.java:80) ~[intermediary-server.jar:?]
at net.minecraft.server.Main.method_29734(Main.java:180) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:260) [intermediary-server.jar:?]
at net.minecraft.server.Main.main(Main.java:179) [intermediary-server.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Exception in thread "main" [19:43:03] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
[19:43:03] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:58)
[19:43:03] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
[19:43:03] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:116)
[19:43:03] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
[19:43:03] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
[19:43:03] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:70)
[19:43:03] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
[19:43:03] [main/INFO]: [STDERR]: ... 1 more
[19:43:03] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[19:43:03] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:43:03] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[19:43:03] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:43:03] [main/INFO]: [STDERR]: at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[19:43:03] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
[19:43:03] [main/INFO]: [STDERR]: ... 2 more
[19:43:03] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[19:43:03] [main/INFO]: [STDERR]: at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
[19:43:03] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[19:43:03] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
[19:43:03] [main/INFO]: [STDERR]: ... 7 more
[19:43:03] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[19:43:03] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:43:03] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[19:43:03] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:43:03] [main/INFO]: [STDERR]: at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[19:43:03] [main/INFO]: [STDERR]: at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[19:43:03] [main/INFO]: [STDERR]: ... 9 more
[19:43:03] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[19:43:03] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
[19:43:03] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
[19:43:03] [main/INFO]: [STDERR]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[19:43:03] [main/INFO]: [STDERR]: at net.minecraft.class_32$class_5143.method_27427(class_32.java:310)
[19:43:03] [main/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:279)
[19:43:03] [main/INFO]: [STDERR]: at net.minecraft.class_3176.<init>(class_3176.java:80)
[19:43:03] [main/INFO]: [STDERR]: at net.minecraft.server.Main.method_29734(Main.java:180)
[19:43:03] [main/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:260)
[19:43:03] [main/INFO]: [STDERR]: at net.minecraft.server.Main.main(Main.java:179)
[19:43:03] [main/INFO]: [STDERR]: ... 14 more
[19:43:03] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.simpleauth.json:MixinWorldSaveHandler] from phase [DEFAULT] in config [mixins.simpleauth.json] FAILED during APPLY
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[19:43:03] [main/INFO]: [STDERR]: ... 26 more
[19:43:03] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_29::fileExists with priority 1000 cannot inject into net/minecraft/class_29::method_261(Lnet/minecraft/class_1657;)Lnet/minecraft/class_2487; merged by org.cardboardpowered.mixin.world.MixinWorldSaveHandler with priority 1000 [PREINJECT Applicator Phase -> mixins.simpleauth.json:MixinWorldSaveHandler -> Prepare Injections -> -> handler$zhh000$fileExists(Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2487;Ljava/io/File;)V -> Prepare]
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[19:43:03] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[19:43:03] [main/INFO]: [STDERR]: ... 26 more
```

**Comment by thefastcomputer** [comment]
same thing for me
