### ISSUE TITLE
EntityAddToWorldEvent may only be triggered synchronously

### ISSUE THREAD

**Issue by davidalb97** [BukkitFabric/bukkit4fabric#273]
I found an incompatibility with 4 mods on "Preparing start region for world minecraft:the_nether" phase.
One of the mods ([OpenLoader](https://www.curseforge.com/minecraft/mc-mods/open-loader)) allows users to load datapacks as if they were mods. This mod in particular does not cause the problem, the datapack that it loads does. 
One of the mods ([William Wyther's Overhauled Overworld](https://www.curseforge.com/minecraft/mc-mods/william-wythers-overhauled-overworld)) also exists as a [datapack](https://www.planetminecraft.com/data-pack/william-wythers-overhauled-overworld/), the latter is preferred as it is more stable around other structure mods.
Removing any of the mods (or the datapack) fixes the crash on the server startup.
As this type of crash is very specific, it took me a while to find all offending mods/datapacks.

**Mod list:**
- [adventurez@1.2.11](https://www.curseforge.com/minecraft/mc-mods/adventurez)
- [betternether@5.1.3](https://www.curseforge.com/minecraft/mc-mods/betternether)
- [cardboard@37](https://modrinth.com/mod/cardboard)
- [cloth-config2@5.0.38](https://www.curseforge.com/minecraft/mc-mods/cloth-config) (Required by Adenturez)
- [fabric@0.40.1+1.17](https://www.curseforge.com/minecraft/mc-mods/fabric-api) (Required by Adenturez, Better Nether, Cardboard)
- [openloader@3.0.1](https://www.curseforge.com/minecraft/mc-mods/open-loader) (Required by WWOO dapack if used)
- [william-wythers-overhauled-overworld@1.6](https://www.curseforge.com/minecraft/mc-mods/william-wythers-overhauled-overworld) (If used instead of the datapack)

**Datapack list**: (loaded with [openloader](https://www.curseforge.com/minecraft/mc-mods/open-loader))
- [William Wythers Overhauled Overworld](https://www.planetminecraft.com/data-pack/william-wythers-overhauled-overworld/) (If used instead of the mod)

**How to reproduce:**
- Option 1 (WWOO as a dapack):
  1. Use seed: `3097733192417250332`
  2. Install all of the mods on the mod list to the `/mods` directory (**except WWOO fabric mod**);
  3. Install the datapacks from the datapack list into the `/config/openloader/data` directory;
  4. Run the server and it should crash during the "Preparing start region for world minecraft:the_nether" phase.
- Option 2 (WWOO as a fabric mod):
  1. Use seed: `3097733192417250332`
  2. Install all of the mods on the mod list to the `/mods` directory;
  3. **Do not** install neither OpenLoader nor WWOO dapack;
  4. Run the server and it should crash during the "Preparing start region for world minecraft:the_nether" phase.

**Workaround:**
- Option 1: Remove one mod of the following mods of your choice from the `/mods` directory:
  - Adventurez
  - Better Nether
  - Cardboard
  - OpenLoader (Also disables the datapack)
- Option 2: Remove the datapack  from the `/config/openloader/data` directory.

**Full server log:** https://pastebin.com/4eZfh0ux

**Crash log:**
```
[Worker-Main-10/INFO]: Preparing spawn area: 100%
[Worker-Main-9/INFO]: Preparing spawn area: 100%
[Worker-Main-7/WARN]: Worker-Main-7 died
java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[intermediary-server.jar:?]
        at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[intermediary-server.jar:?]
        at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[intermediary-server.jar:?]
        at net.minecraft.class_3846.run(class_3846.java:102) ~[intermediary-server.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: net.minecraft.class_148: Feature placement
        at net.minecraft.class_3898.method_17225(class_3898.java:568) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
        at net.minecraft.class_3898.method_17224(class_3898.java:550) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
        ... 11 more
Caused by: java.lang.IllegalStateException: EntityAddToWorldEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:612) ~[paper-api-1.17-dev.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.17-dev.jar:?]
        at net.minecraft.class_3218$class_5526.handler$zbc000$validateEntityBF(class_3218.java:1561) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1439) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1404) ~[intermediary-server.jar:?]
        at net.minecraft.class_5579.method_31847(class_5579.java:210) ~[intermediary-server.jar:?]
        at net.minecraft.class_5579.method_31820(class_5579.java:180) ~[intermediary-server.jar:?]
        at net.minecraft.class_5579.method_31818(class_5579.java:161) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218.method_14175(class_3218.java:808) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218.method_8649(class_3218.java:759) ~[intermediary-server.jar:?]
        at net.adventurez.entity.BlazeGuardianEntity.<init>(BlazeGuardianEntity.java:79) ~[%5BRPG%5Dadventurez-1.2.11%5BCloth-Config%5D.jar:?]
        at net.minecraft.class_1299.method_5883(class_1299.java:475) ~[intermediary-server.jar:?]
        at net.minecraft.class_3390$class_3402.handler$zkd000$generateMixin(class_3390.java:836) ~[intermediary-server.jar:?]
        at net.minecraft.class_3390$class_3402.method_14931(class_3390.java:739) ~[intermediary-server.jar:?]
        at net.minecraft.class_3449.method_14974(class_3449.java:97) ~[intermediary-server.jar:?]
        at net.minecraft.class_1959.method_28401(class_1959.java:366) ~[intermediary-server.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189) ~[?:?]
        at it.unimi.dsi.fastutil.longs.LongIterator.forEachRemaining(LongIterator.java:53) ~[intermediary-server.jar:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at net.minecraft.class_1959.method_8702(class_1959.java:365) ~[intermediary-server.jar:?]
        at net.minecraft.class_2794.handler$zlh000$customPopulate(class_2794.java:538) ~[intermediary-server.jar:?]
        at net.minecraft.class_2794.method_12102(class_2794.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_2806.method_12151(class_2806.java:100) ~[intermediary-server.jar:?]
        at net.minecraft.class_2806.method_12154(class_2806.java:231) ~[intermediary-server.jar:?]
        at net.minecraft.class_3898.method_17225(class_3898.java:556) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
        at net.minecraft.class_3898.method_17224(class_3898.java:550) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
        ... 11 more
```

**Comment by davidalb97** [comment]
I could not replicate the issue on Cardboard version 45, closing issue.

Modlist:
- adventurez@1.4.3
- bclib@0.5.5
- betternether@5.3.12
- cardboard@45
- cloth-config2@5.1.40
- icommon@1.17
- openloader@3.0.1

Datapacks:
- william-wythers-overhauled-overworld-for-1-17-e2380-e3270
- phantasmal-forest-addon-for-william-wythers-overhauled-overworld
- primordial-shores-add-on-for-william-wythers-overhauled-overworld
- william-wythers-open-oceans-add-on-for-overhauled-overworld
