### ISSUE TITLE
Colouring Sheep not possible

### ISSUE THREAD

**Issue by MartinaeyNL** [BukkitFabric/bukkit4fabric#286]
Minecraft: Version 1.17.1, Fabric w/ Cardboard installed
Mods:  Only Cardboard and Lithium
Plugins: Only Essentials and CoreProtect

I don't know whether this is just something that is not an implemented Event yet,
or whether this is a glitch. When trying to colour sheep it cancels the action and sends this stacktrace:

```
[17:27:20] [Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: class org.cardboardpowered.impl.entity.AnimalsImpl cannot be cast to class org.bukkit.entity.Sheep (org.cardboardpowered.impl.entity.AnimalsImpl and org.bukkit.entity.Sheep are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @a38c7fe)
        at net.minecraft.class_1769.method_7847(class_1769.java:539) ~[intermediary-server.jar:?]
        at net.minecraft.class_1799.method_7920(class_1799.java:398) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_7287(class_1657.java:1072) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244$1.method_33897(class_3244.java:1308) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244$1.method_34219(class_3244.java:1319) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12062(class_3244.java:1305) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[17:27:21] [Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: class org.cardboardpowered.impl.entity.AnimalsImpl cannot be cast to class org.bukkit.entity.Sheep (org.cardboardpowered.impl.entity.AnimalsImpl and org.bukkit.entity.Sheep are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @a38c7fe)
        at net.minecraft.class_1769.method_7847(class_1769.java:539) ~[intermediary-server.jar:?]
        at net.minecraft.class_1799.method_7920(class_1799.java:398) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_7287(class_1657.java:1072) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244$1.method_33897(class_3244.java:1308) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244$1.method_34219(class_3244.java:1319) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12062(class_3244.java:1305) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[17:27:21] [Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: class org.cardboardpowered.impl.entity.AnimalsImpl cannot be cast to class org.bukkit.entity.Sheep (org.cardboardpowered.impl.entity.AnimalsImpl and org.bukkit.entity.Sheep are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @a38c7fe)
        at net.minecraft.class_1769.method_7847(class_1769.java:539) ~[intermediary-server.jar:?]
        at net.minecraft.class_1799.method_7920(class_1799.java:398) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_7287(class_1657.java:1072) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244$1.method_33897(class_3244.java:1308) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244$1.method_34219(class_3244.java:1319) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12062(class_3244.java:1305) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[17:27:22] [Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: class org.cardboardpowered.impl.entity.AnimalsImpl cannot be cast to class org.bukkit.entity.Sheep (org.cardboardpowered.impl.entity.AnimalsImpl and org.bukkit.entity.Sheep are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @a38c7fe)
        at net.minecraft.class_1769.method_7847(class_1769.java:539) ~[intermediary-server.jar:?]
        at net.minecraft.class_1799.method_7920(class_1799.java:398) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_7287(class_1657.java:1072) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244$1.method_33897(class_3244.java:1308) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244$1.method_34219(class_3244.java:1319) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12062(class_3244.java:1305) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[17:27:22] [Netty Epoll Server IO #7/INFO]: §r§eGlamingo§r §8» §rserver shit
[17:27:22] [Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: class org.cardboardpowered.impl.entity.AnimalsImpl cannot be cast to class org.bukkit.entity.Sheep (org.cardboardpowered.impl.entity.AnimalsImpl and org.bukkit.entity.Sheep are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @a38c7fe)
        at net.minecraft.class_1769.method_7847(class_1769.java:539) ~[intermediary-server.jar:?]
        at net.minecraft.class_1799.method_7920(class_1799.java:398) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_7287(class_1657.java:1072) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244$1.method_33897(class_3244.java:1308) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244$1.method_34219(class_3244.java:1319) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12062(class_3244.java:1305) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
Anyone an idea?

**Comment by noahammond** [comment]
Issue still persists in 1.18, anyone know a fix/workaround?

**Comment by Saffy27** [comment]
Issue still persists in 1.21.11. Can some PLEASE fix this?

[02:17:01] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2824@566350ce, suppressing error
java.lang.ClassCastException: class org.cardboardpowered.impl.entity.CraftAnimals cannot be cast to class org.bukkit.entity.Sheep (org.cardboardpowered.impl.entity.CraftAnimals and org.bukkit.entity.Sheep are in unnamed module of loader 'knot' @1bce4f0a)
at knot//net.minecraft.class_1769.method_7847(class_1769.java:541)
at knot//net.minecraft.class_1799.method_7920(class_1799.java:601)
at knot//net.minecraft.class_1657.method_7287(class_1657.java:943)
at knot//net.minecraft.class_3244$1.method_33897(class_3244.java:1869)
at knot//net.minecraft.class_3244$1.method_34219(class_3244.java:1881)
at knot//net.minecraft.class_2824$class_5909.method_34213(class_2824.java:133)
at knot//net.minecraft.class_2824.method_34209(class_2824.java:83)
at knot//net.minecraft.class_3244.method_12062(class_3244.java:1862)
at knot//net.minecraft.class_2824.method_12251(class_2824.java:63)
at knot//net.minecraft.class_2824.method_65081(class_2824.java:17)
at knot//net.minecraft.class_11980$class_11981.method_74450(class_11980.java:55)
at knot//net.minecraft.class_11980.method_74449(class_11980.java:38)
at knot//net.minecraft.server.MinecraftServer.method_76677(MinecraftServer.java:1047)
at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:771)
at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:301)
at java.base/java.lang.Thread.run(Thread.java:1583)
