### ISSUE TITLE
Crash Issue with Origins 1.2.0 installed

### ISSUE THREAD

**Issue by daniellegge** [BukkitFabric/bukkit4fabric#295]
Minecraft 1.18
JRE 1.17
Fabric API 0.43.1
Origins Mod 1.2.0

`net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:601)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at net.minecraft.class_1299.<clinit>(class_1299.java:164)
	at net.minecraft.class_3103.<clinit>(class_3103.java:28)
	at net.minecraft.class_3031.<clinit>(class_3031.java:81)
	at net.minecraft.class_6800.<clinit>(class_6800.java:19)
	at net.minecraft.class_6803.method_39702(class_6803.java:20)
	at net.minecraft.class_5458.method_30566(class_5458.java:78)
	at java.base/java.util.LinkedHashMap.forEach(Unknown Source)
	at net.minecraft.class_5458.<clinit>(class_5458.java:77)
	at net.minecraft.class_2378.<clinit>(class_2378.java:269)
	at net.minecraft.class_2966.method_12851(class_2966.java:49)
	at net.minecraft.server.Main.main(Main.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	... 7 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 23 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229)
	... 26 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method copyInventoryWhenKeeping(Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in apoli.mixins.json:ServerPlayerEntityMixin from mod apoli failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Apoli-1.18-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 29 more
`

[2021-12-03-4.log.gz](https://github.com/CardboardPowered/cardboard/files/7652555/2021-12-03-4.log.gz)

**Comment by neerfix** [comment]
Yup, i've same problem. When i delete Origins 1.2.0, cardboard works.

**Comment by pisaiah** [comment]
Should be fixed now.
