### ISSUE TITLE
Crash when the world is generated.

### ISSUE THREAD

**Issue by RE4ERKA** [BukkitFabric/bukkit4fabric#299]
```
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot read field "worlds" because "org.bukkit.craftbukkit.CraftServer.INSTANCE" is null
	at net.minecraft.class_1937.handler$zzn000$init(class_1937.java:1162)
	at net.minecraft.class_1937.<init>(class_1937.java:148)
	at net.minecraft.class_3218.<init>(class_3218.java:206)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:371)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:327)
	at net.minecraft.class_1132.method_3823(class_1132.java:72)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
[latest.log](https://github.com/CardboardPowered/cardboard/files/7687168/latest.log)

**Comment by pisaiah** [comment]
Cardboard currently only supports servers.
