### ISSUE TITLE
Something is wrong with nms scoreboard, error on startup

### ISSUE THREAD

**Issue by SzczurekYT** [BukkitFabric/bukkit4fabric#305]
Hello

I'm trying to get my own plugin to work on Cardboard. When the server starts up it throws NoDefClassFoundError when enabling my plugin. I tested and it works on normal paper server, it uses spigot api with mojang maps - it uses nms.

Here is the error
`[14:50:47] [Server thread/FATAL]: Error occurred while enabling MagnolieDeathSystem v1.0-1.17 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/scoreboard/CraftScoreboard
        at me.szczurekyt.magnoliedeathsystem.GhostManager.<init>(GhostManager.java:27) ~[?:?]
        at me.szczurekyt.magnoliedeathsystem.DeathManager.<init>(DeathManager.java:15) ~[?:?]
        at me.szczurekyt.magnoliedeathsystem.DeathPlugin.onEnable(DeathPlugin.java:18) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:257) ~[Cardboard-1.17-1.18.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:306) ~[Cardboard-1.17-1.18.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.17-dev.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:478) ~[Cardboard-1.17-1.18.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:409) ~[Cardboard-1.17-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zzb000$afterWorldLoad(MinecraftServer.java:1909) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:342) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:182) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]`
        
Full log:
[latest.log](https://github.com/CardboardPowered/cardboard/files/7739335/latest.log)

And if you want I can give you acces to private repo with plugins code.

I don't look for compatibility for this one plugin, but I'm looking asking for general implementation that will work overall.
Is the scoreboard (NMS) implemented? Or not yet?

Thanks, this mod should get more attention, as It has good chance to work.

**Comment by L0rdLogan** [comment]
Nms has issues with cardboard at the moment, cardboard is not complete, your plugin uses a class that is not yet implanted into cardboard

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: SzczurekYT ***@***.***>
Sent: Saturday, December 18, 2021 1:58:04 PM
To: CardboardPowered/cardboard ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CardboardPowered/cardboard] Something is wrong with nms scoreboard, error on startup (Issue #305)


Hello

I'm trying to get my own plugin to work on Cardboard. When the server starts up it throws NoDefClassFoundError when enabling my plugin. I tested and it works on normal paper server, it uses spigot api with mojang maps - it uses nms.

Here is the error
[14:50:47] [Server thread/FATAL]: Error occurred while enabling MagnolieDeathSystem v1.0-1.17 (Is it up to date?) java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/scoreboard/CraftScoreboard at me.szczurekyt.magnoliedeathsystem.GhostManager.<init>(GhostManager.java:27) ~[?:?] at me.szczurekyt.magnoliedeathsystem.DeathManager.<init>(DeathManager.java:15) ~[?:?] at me.szczurekyt.magnoliedeathsystem.DeathPlugin.onEnable(DeathPlugin.java:18) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:257) ~[Cardboard-1.17-1.18.jar:?] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:306) ~[Cardboard-1.17-1.18.jar:?] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.17-dev.jar:?] at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:478) ~[Cardboard-1.17-1.18.jar:?] at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:409) ~[Cardboard-1.17-1.18.jar:?] at net.minecraft.server.MinecraftServer.handler$zzb000$afterWorldLoad(MinecraftServer.java:1909) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:342) ~[server-intermediary.jar:?] at net.minecraft.class_3176.method_3823(class_3176.java:182) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?] at java.lang.Thread.run(Thread.java:833) [?:?]

Full log:
latest.log<https://github.com/CardboardPowered/cardboard/files/7739335/latest.log>

And if you want I can give you acces to private repo with plugins code.

I don't look for compatibility for this one plugin, but I'm looking asking for general implementation that will work overall.
Is the scoreboard (NMS) implemented? Or not yet?

Thanks, this mod should get more attention, as It has good chance to work.

**Comment by SzczurekYT** [comment]
That's what I thinked.

**Comment by SzczurekYT** [comment]
Maybe I could contribute to the project? But how? There aren't any docs. Also I'm not very familiar with modding so this can be a problem.
