### ISSUE TITLE
Better Minecraft fabric server crashes with carboard.

### ISSUE THREAD

**Issue by MrLunchbox** [BukkitFabric/bukkit4fabric#313]
there must be an incompatible mod in the pack somewhere and i am not smart enough to locate it but hopefully the error might help.
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
        at net.minecraft.class_1299.<clinit>(class_1299.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
        at net.minecraft.class_3031.<clinit>(class_3031.java:81) ~[server-intermediary.jar:?]
        at net.minecraft.class_6800.<clinit>(class_6800.java:19) ~[server-intermediary.jar:?]
        at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
        ... 7 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_1299.<clinit>(class_1299.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
        at net.minecraft.class_3031.<clinit>(class_3031.java:81) ~[server-intermediary.jar:?]
        at net.minecraft.class_6800.<clinit>(class_6800.java:19) ~[server-intermediary.jar:?]
        at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
        ... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_1299.<clinit>(class_1299.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
        at net.minecraft.class_3031.<clinit>(class_3031.java:81) ~[server-intermediary.jar:?]
        at net.minecraft.class_6800.<clinit>(class_6800.java:19) ~[server-intermediary.jar:?]
        at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
        ... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method copyAbilitiesAfterRespawn(Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in mixins.playerabilitylib.common.json:ServerPlayerEntityMixin from mod playerabilitylib failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap pal-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_1299.<clinit>(class_1299.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
        at net.minecraft.class_3031.<clinit>(class_3031.java:81) ~[server-intermediary.jar:?]
        at net.minecraft.class_6800.<clinit>(class_6800.java:19) ~[server-intermediary.jar:?]
        at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
        ... 7 more
hopefully this isnt too bad of an issue and would love some attention on the matter. Thanks for taking a look if you can!

**Comment by L-m-b** [comment]
In my case the wanderign trader has been crashing the game with cardboard, makes no sense to me and i would prefer it to not do that every time that damned villager comes to steal emeralds.

**Comment by MrLunchbox** [comment]
Interesting ill take a look at it and honestly waNDERING TRADER NEEDS TO GET A LIFE!

**Comment by MrLunchbox** [comment]
Sadly the problem occurs on startup of the server so it shouldn't be the trader.

**Comment by jonathansawers** [comment]
Also experiencing this issue
