### ISSUE TITLE
Cardboard instigating crashes because it cannot figure out how to class a horse entity, making the wandering trader crash the server

### ISSUE THREAD

**Issue by L-m-b** [BukkitFabric/bukkit4fabric#314]
Caused by: java.lang.ClassCastException: class org.cardboardpowered.impl.entity.LivingEntityImpl cannot be cast to class org.bukkit.entity.AbstractHorse (org.cardboardpowered.impl.entity.LivingEntityImpl and org.bukkit.entity.AbstractHorse are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @146ba0ac)
        at net.minecraft.entity.passive.HorseBaseEntity.handler$zea000$cardboard$setInvOwner(HorseBaseEntity:1200) ~[?:?]
        at net.minecraft.entity.passive.HorseBaseEntity.onChestedStatusChanged(HorseBaseEntity:312) ~[?:?]
        at net.minecraft.entity.passive.HorseBaseEntity.<init>(HorseBaseEntity:127) ~[?:?]
        at net.minecraft.entity.passive.AbstractDonkeyEntity.<init>(AbstractDonkeyEntity:27) ~[?:?]
        at net.minecraft.entity.passive.LlamaEntity.<init>(LlamaEntity:78) ~[?:?]
        at net.minecraft.entity.passive.TraderLlamaEntity.<init>(TraderLlamaEntity:27) ~[?:?]
        at net.minecraft.entity.EntityType.create(EntityType:475) ~[?:?]
        at net.minecraft.entity.EntityType.create(EntityType:344) ~[?:?]
        at net.minecraft.entity.EntityType.spawn(EntityType:332) ~[?:?]
        at net.minecraft.world.WanderingTraderManager.spawnLlama(WanderingTraderManager:143) ~[?:?]
        at net.minecraft.world.WanderingTraderManager.trySpawn(WanderingTraderManager:124) ~[?:?]
        at net.minecraft.world.WanderingTraderManager.spawn(WanderingTraderManager:88) ~[?:?]
        at net.minecraft.server.world.ServerWorld.tickSpawners(ServerWorld:396) ~[?:?]
        at net.minecraft.server.world.ServerChunkManager.tickChunks(ServerChunkManager:387) ~[?:?]
        at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager:325) ~[?:?]
        at net.minecraft.server.world.ServerWorld.tick(ServerWorld:308) ~[?:?]
        at net.minecraft.server.MinecraftServer.md4da223$lambda$tickWorlds$0$4(MinecraftServer:7786) ~[server-intermediary.jar:?]
        at wearblackallday.dimthread.DimThread.swapThreadsAndRun(DimThread.java:34) ~[DimThread-1.2.6.jar:?]
        at net.minecraft.server.MinecraftServer.md4da223$lambda$tickWorlds$1$3(MinecraftServer:7784) ~[server-intermediary.jar:?]
        at wearblackallday.util.ThreadPool.lambda$execute$1(ThreadPool.java:49) ~[com_github_wearblackallday_javau-bd58640372-66147bdb5f3fcaf7.jar:?]
        at wearblackallday.util.ThreadPool.lambda$execute$0(ThreadPool.java:43) ~[com_github_wearblackallday_javau-bd58640372-66147bdb5f3fcaf7.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        ... 1 more
[08:42:59] [Server thread/ERROR]: This crash report has been saved to: C:\Users\LukeB\Desktop\Fabric+spigot\.\crash-reports\crash-2022-01-07_08.42.59-server.txt
[08:42:59] [Server thread/INFO]: Disabling Essentials v2.19.3-dev+7-bb88a6a
[08:42:59] [Server thread/INFO]: Stopping server
[08:42:59] [Server thread/INFO]: Saving players
[08:42:59] [Server thread/INFO]: Saving worlds
[08:42:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[08:42:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[08:42:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[08:42:59] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[08:42:59] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[08:42:59] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[08:42:59] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[08:42:59] [Server thread/INFO]: Goodbye!

**Comment by TwoPointInfinity** [comment]
same. horses make the game crash. pretty much makes this mod unusable for 1.18.1 rn

**Comment by Theslees** [comment]
Wow. I'm going to have to disable them for my server too then I guess. They've been causing Fatal crashes recently lmao.
