### ISSUE TITLE
Server crashes quite often in 1.18.1

### ISSUE THREAD

**Issue by epicbuilder2007** [BukkitFabric/bukkit4fabric#318]
My server crashes once per day or so, with the error:

> Description: Exception ticking world

>java.lang.ClassCastException: class org.cardboardpowered.impl.entity.LivingEntityImpl cannot be cast to class org.bukkit.entity.AbstractHorse (org.cardboardpowered.impl.entity.LivingEntityImpl and org.bukkit.entity.AbstractHorse are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @224edc67)
	at net.minecraft.class_1496.handler$zbn000$cardboard$setInvOwner(class_1496.java:1200)
	at net.minecraft.class_1496.method_6721(class_1496.java:312)
	at net.minecraft.class_1496.<init>(class_1496.java:127)
	at net.minecraft.class_1506.<init>(class_1506.java:32)
	at net.minecraft.class_1299.method_5883(class_1299.java:475)
	at net.minecraft.class_3218.method_18203(class_3218.java:433)
	at net.minecraft.class_3215.method_14161(class_3215.java:380)
	at net.minecraft.class_3215.method_12127(class_3215.java:325)
	at net.minecraft.class_3218.method_18765(class_3218.java:308)
	at net.minecraft.server.MinecraftServer.redirect$znj000$fixUpdateSuppressionCrashTick(MinecraftServer.java:4754)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.handler$zgj000$modifiedRunLoop(MinecraftServer.java:3856)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

Full crash file here:
[crash-2022-01-22_05.27.47-server.txt](https://github.com/CardboardPowered/cardboard/files/7917747/crash-2022-01-22_05.27.47-server.txt)

**Comment by someone1995** [comment]
horses aren't compatible with cardboard by now

**Comment by pisaiah** [comment]
Should be fixed now.
