### ISSUE TITLE
 Bewitchment and Cardboard crashed

### ISSUE THREAD

**Issue by Eistarossa** [BukkitFabric/bukkit4fabric#320]
Hello.
Sorry for my English.

**My server:**
- Minecraft 1.18.1
- Java 17
- Fabric Loader 0.12.12
- Fabric API 0.46.1+1.18
- Cardboard-1.17-1.18
- iCommon-Fabric-1.18

**Plugins:**
- Chunky-1.2.164
- EssentialsX-2.19.3-dev+9-5c46bea
- EssentialsXChat-2.19.3-dev+9-5c46bea
- EssentialsXSpawn-2.19.3-dev+9-5c46bea
- FastAsyncWorldEdit-Bukkit-2.0.0
- LuckPerms-Bukkit-5.3.86

**Mods:**
- Bewitchment-1.18-6
- C2me-fabric-mc1.18.1-0.2.0+alpha.6.25-all
- Cloth-config-6.1.48-fabric
- Ferritecore-4.0.0-fabric
- Krypton-0.1.6
- Lazydfu-0.1.2
- Lithium-fabric-mc1.18.1-0.7.7
- Patchouli-1.18.1-64-FABRIC
- Pehkui-3.1.0+1.14.4-1.18.1
- Trinkets-3.1.0

**When you start with the _Bewitchment_ and _Cardboard_ with pugins it constantly crashes. I can not understand what is the conflict between mods and plugins. When I run it without _Cardboard_ but with _Bewitchment_ everything works. When run without _Bewitchment_ everything works stably. All required mods for _Bewitchment_  installed and tested. Without _Bewitchment_ , but with his necessary mods, everything works.**

**Please help me fix this problem or tell me how to set it up correctly.**

Link to my server uploaded to google drive:
[Server](https://drive.google.com/file/d/1YzocqCeCFbvZB37Uu8Dyb6oyl6L8YOzN/view?usp=sharing)

**Logs:**
```
C:\Users\***\Desktop\Server>java -Xmx2G -jar fabric-server-launch.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[23:52:26] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[23:52:28] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[23:52:28] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9565 recommends any version of fabric-textures-v0,
 which is disabled for this environment (client/server only)!
         - You should install any version of fabric-textures-v0 for the optimal experience.
[23:52:28] [main/INFO]: Loading 64 mods:
        - bewitchment 1.18-6
        - c2me 0.2.0+alpha.6.25
        - cardboard 43
        - cardinal-components-base 4.0.0 via trinkets
        - cardinal-components-entity 4.0.0 via trinkets
        - cloth-basic-math 0.6.0 via cloth-config
        - cloth-config 6.1.48
        - com_github_isaiahpatton_specialsource master-SNAPSHOT via cardboard
        - com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
        - elativitymc_c2me-fabric_ver_1_18_libs_ 0.2.0+alpha.6.25 via c2me
        - fabric 0.46.1+1.18
        - fabric-api-base 0.4.1+b4f4f6cd65 via fabric
        - fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
        - fabric-biome-api-v1 6.0.1+ded849a965 via fabric
        - fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
        - fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
        - fabric-containers-v0 0.1.18+d154e2c665 via fabric
        - fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
        - fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
        - fabric-dimensions-v1 2.1.9+a1d9bbf565 via fabric
        - fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
        - fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
        - fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
        - fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
        - fabric-item-api-v1 1.3.0+691a79b565 via fabric
        - fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
        - fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
        - fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
        - fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
        - fabric-mining-levels-v0 0.1.8+b4f4f6cd65 via fabric
        - fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
        - fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
        - fabric-object-builder-api-v1 1.11.1+3b82842e65 via fabric
        - fabric-object-builders-v0 0.7.9+3ac43d9565 via fabric
        - fabric-particles-v1 0.2.9+526dc1ac65 via fabric
        - fabric-permissions-api-v0 0.1-SNAPSHOT via bewitchment
        - fabric-registry-sync-v0 0.9.0+befed49e65 via fabric
        - fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
        - fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
        - fabric-resource-conditions-api-v1 1.0.1+13eda06565 via fabric
        - fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
        - fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
        - fabric-structure-api-v1 2.1.0+0a73a6c265 via fabric
        - fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
        - fabric-tool-attribute-api-v1 1.3.5+fb3b57b465 via fabric
        - fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
        - fabricloader 0.12.12
        - ferritecore 4.0.0
        - fiber 0.23.0-2 via patchouli
        - icommon 1.18
        - impersonate 2.4.0 via bewitchment
        - java 17
        - kanos_config 0.1.4+1.14.4-1.17.1 via pehkui
        - krypton 0.1.6
        - lazydfu 0.1.2
        - lithium 0.7.7
        - minecraft 1.18.1
        - patchouli 1.18.1-64-FABRIC
        - pehkui 3.1.0+1.14.4-1.18.1
        - playerabilitylib 1.5.0 via bewitchment
        - reach-entity-attributes 2.1.1 via bewitchment
        - step-height-entity-attribute 1.0.0 via bewitchment
        - terraform-wood-api-v1 2.0.2 via bewitchment
        - trinkets 3.1.0
[23:52:29] [main/WARN]: Mod `com_github_isaiahpatton_specialsource` (master-SNAPSHOT) 
			does not respect SemVer - comparison support is limited.
[23:52:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 
			Source=file:/C:/Users/***/Desktop/Server/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar 
			Service=Knot/Fabric Env=SERVER
[23:52:30] [main/INFO]: Compatibility level set to JAVA_16
[23:52:30] [main/INFO]: Compatibility level set to JAVA_17
[23:52:31] [main/INFO]: Configuration loaded successfully after 487.7164ms
[23:52:31] [main/INFO]: Successfully loaded configuration for C2ME
[23:52:31] [main/INFO]: Initializing C2ME Compatibility Module
[23:52:31] [main/INFO]: Loading Libraries...
[23:52:31] [main/INFO]: Debug: Loading library paper-api-1.17-dev.jar
[23:52:31] [main/INFO]: Debug: Loading library sqlite-jdbc-3.21.0.1.jar
[23:52:31] [main/INFO]: Debug: Loading library mysql-connector-java-5.1.46.jar
[23:52:31] [main/INFO]: Debug: Loading library commons-lang-2.6.jar
[23:52:31] [main/INFO]: Debug: Loading library commons-collections4-4.4.jar
[23:52:31] [main/INFO]: Debug: Loading library commons-collections-3.2.1.jar
[23:52:31] [main/INFO]: Debug: Loading library gson-2.8.6.jar
[23:52:31] [main/INFO]: Debug: Loading library jline-3.19.0.jar
[23:52:31] [main/INFO]: Loaded configuration file for Lithium: 88 options available, 1 override(s) found
[23:52:32] [main/WARN]: Error loading class: io/github/apace100/apoli/power/PreventItemUsePower (java.lang.ClassNotFoundException: 
			io/github/apace100/apoli/power/PreventItemUsePower)
[23:52:32] [main/WARN]: @Mixin target io.github.apace100.apoli.power.PreventItemUsePower was not found 
			bewitchment.mixins.json:integration.origins.PreventItemUsePowerMixin
[23:52:33] [main/INFO]: =======================================================
[23:52:33] [main/INFO]:  iCommon - Isaiah's common library for mods.
[23:52:33] [main/INFO]:  Copyright (c) 2018-2021 by Isaiah. Running on MC 1.18.1
[23:52:33] [main/INFO]: =======================================================
[23:52:33] [main/INFO]: Applying mixin: MixinMinecraftServer...
[23:52:33] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule
			'mixin.world.player_chunk_tick' (added by mods [c2me, krypton]) disables it and children
[23:52:33] [main/INFO]: Adding mixins: [None]
[23:52:33] [main/INFO]: Applying mixin: R1_18.MixinEntity...
[23:52:33] [main/INFO]: Applying mixin: R1_18.MixinPlayer...
[23:52:33] [main/INFO]: Applying mixin: R1_18.MixinBlockEntity...
[23:52:33] [main/INFO]: Applying mixin: R1_18.MixinChestBlockEntity...
[23:52:33] [main/INFO]: Applying mixin: R1_18.MixinCampfireBlockEntity...
[23:52:33] [main/INFO]: Applying mixin: R1_18.MixinScreenHandler...
[23:52:33] [main/INFO]: Applying mixin: R1_18.MixinChunkGenerator...
[23:52:33] [main/INFO]: Applying mixin: R1_18.MixinPersistentStateManager...
[23:52:33] [main/INFO]: Applying mixin: R1_18.MixinPlayerManager...
[23:52:33] [main/INFO]: Applying mixin: R1_18.MixinHeighttmap...
[23:52:34] [main/INFO]: Applying mixin: R1_18.MixinWorld_18...
[23:52:47] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: 
		Mixin transformation of net.minecraft.class_3222 failed
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
        at net.minecraft.class_1299.<clinit>(class_1299.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
        at net.minecraft.class_3031.<clinit>(class_3031.java:81) ~[server-intermediary.jar:?]
        at net.minecraft.class_6800.<clinit>(class_6800.java:19) ~[server-intermediary.jar:?]
        at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
        ... 7 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_1299.<clinit>(class_1299.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
        at net.minecraft.class_3031.<clinit>(class_3031.java:81) ~[server-intermediary.jar:?]
        at net.minecraft.class_6800.<clinit>(class_6800.java:19) ~[server-intermediary.jar:?]
        at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
        ... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) 
		~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) 
		~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
		~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_1299.<clinit>(class_1299.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
        at net.minecraft.class_3031.<clinit>(class_3031.java:81) ~[server-intermediary.jar:?]
        at net.minecraft.class_6800.<clinit>(class_6800.java:19) ~[server-intermediary.jar:?]
        at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
        ... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: 
		Callback method copyAbilitiesAfterRespawn(Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)
			V in mixins.playerabilitylib.common.json:ServerPlayerEntityMixin from mod playerabilitylib failed injection check,
			(0/1) succeeded. Scanned 1 target(s). Using refmap pal-refmap.json
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) 
			~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381)
			~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
			~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
			~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) 
			~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) 
			~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) 
			~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) 
			~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) 
			~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) 
			~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
			~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
			~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
			~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_1299.<clinit>(class_1299.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
        at net.minecraft.class_3031.<clinit>(class_3031.java:81) ~[server-intermediary.jar:?]
        at net.minecraft.class_6800.<clinit>(class_6800.java:19) ~[server-intermediary.jar:?]
        at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
        ... 7 more

C:\Users\***\Desktop\Server>pause
Press any key to continue . . .
```

**Comment by t0int** [comment]
i have this issue too..
