### ISSUE TITLE
ViaVersion/Backwards not working on latest cardboard (server v: 1.18.1)

### ISSUE THREAD

**Issue by Jo580rn3** [BukkitFabric/bukkit4fabric#341]
Everything is up to date, except the server, it's running 1.18.1. Geyser and Floodgate are workin with a few hickups but ViaVersion and ViaBackwards aren't at all. Here are my logs (censored for obvious reasons).

[00:26:20] [Server thread/INFO]: This server is running Cardboard version git-UNKNOWN (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
[00:26:20] [Server thread/INFO]: Debug logging is disabled
[00:26:20] [Server thread/INFO]: Loading Bukkit plugins...
[00:26:21] [Server thread/INFO]: Remapping "plugins\floodgate-spigot.jar"...
[00:26:41] [Server thread/INFO]: [STDOUT]: net/minecraft/class_2535
[00:26:41] [Server thread/INFO]: Loading ViaVersion v4.3.0-22w14a-SNAPSHOT
[00:26:41] [Server thread/FATAL]: null initializing ViaVersion v4.3.0-22w14a-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:104) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:403) ~[Cardboard-1.17-1.18.jar:?]
        at net.minecraft.class_3176.handler$zza000$init(class_3176.java:760) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:160) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
        at java.lang.reflect.Method.invoke(Method.java:561) ~[?:?]
        at com.viaversion.viaversion.bukkit.util.NMSUtil.loadDebugProperty(NMSUtil.java:33) ~[?:?]
        at com.viaversion.viaversion.bukkit.util.NMSUtil.<clinit>(NMSUtil.java:25) ~[?:?]
        ... 7 more

...

[00:26:42] [Server thread/INFO]: Loading ViaBackwards v4.3.0-22w14a-SNAPSHOT
[00:26:42] [Server thread/INFO]: Loading translations...
[00:26:43] [Via-Mappingloader-0/INFO]: Loading 1.10 -> 1.9.4 mappings...
[00:26:43] [Server thread/FATAL]: Cannot invoke "java.util.concurrent.CompletableFuture.whenCompleteAsync(java.util.function.BiConsumer, java.util.concurrent.Executor)" because the return value of "com.viaversion.viaversion.protocol.ProtocolManagerImpl.getMappingLoaderFuture(java.lang.Class)" is null initializing ViaBackwards v4.3.0-22w14a-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.CompletableFuture.whenCompleteAsync(java.util.function.BiConsumer, java.util.concurrent.Executor)" because the return value of "com.viaversion.viaversion.protocol.ProtocolManagerImpl.getMappingLoaderFuture(java.lang.Class)" is null
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.addMappingLoaderFuture(ProtocolManagerImpl.java:456) ~[?:?]
        at com.viaversion.viabackwards.api.BackwardsProtocol.executeAsyncAfterLoaded(BackwardsProtocol.java:44) ~[?:?]
        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.Protocol1_12_2To1_13.registerPackets(Protocol1_12_2To1_13.java:59) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:76) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:187) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:181) ~[?:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:90) ~[?:?]
        at com.viaversion.viabackwards.BukkitPlugin.init(BukkitPlugin.java:48) ~[?:?]
        at com.viaversion.viabackwards.BukkitPlugin.onLoad(BukkitPlugin.java:36) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:403) ~[Cardboard-1.17-1.18.jar:?]
        at net.minecraft.class_3176.handler$zza000$init(class_3176.java:760) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:160) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

...

[00:27:12] [Server thread/WARN]: You are using an outdated version of ViaVersion; please download the newest version from https://ci.viaversion.com/job/ViaVersion/

**Comment by pisaiah** [comment]
can confirm the ViaVersion fabric mod works on 1.21.10
