### ISSUE TITLE
Crash Loop On 1.18.1 Fabric Server

### ISSUE THREAD

**Issue by Flintstonewastaken** [BukkitFabric/bukkit4fabric#344]
Hello! I have a Fabric server running on 1.18.1 and every time, I try to start the server, there is a crash loop that begins with the iCommon library, I assume. The mods in my mod folder are as follows;
- Cardboard
- Croptopia
- Patchouli (Library)
- Cloth Config (Library)
- Create
- Fabric API
- iCommon (Library)
- Lithium
- Phosphor

This is the crash report at the point where everything starts to go wrong.

`09.05 01:38:32 [Server] main/INFO =======================================================
09.05 01:38:32 [Server] main/INFO iCommon - Isaiah's common library for mods.
09.05 01:38:32 [Server] main/INFO Copyright (c) 2018-2021 by Isaiah. Running on MC 1.18.1
09.05 01:38:32 [Server] main/INFO =======================================================
09.05 01:38:32 [Server] main/INFO Applying mixin: MixinMinecraftServer...
09.05 01:38:32 [Server] main/WARN Error loading class: net/minecraft/class_5616 (java.lang.ClassNotFoundException: net/minecraft/class_5616)
09.05 01:38:32 [Server] main/WARN @Mixin target net.minecraft.class_5616 was not found registrate-fabric.mixins.json:accessor.BlockEntityRenderersAccessor from mod registrate-fabric
09.05 01:38:32 [Server] main/INFO Applying mixin: R1_18.MixinEntity...
09.05 01:38:32 [Server] main/INFO Applying mixin: R1_18.MixinPlayer...
09.05 01:38:32 [Server] main/INFO Applying mixin: R1_18.MixinBlockEntity...
09.05 01:38:32 [Server] main/INFO Applying mixin: R1_18.MixinChestBlockEntity...
09.05 01:38:32 [Server] main/INFO Applying mixin: R1_18.MixinCampfireBlockEntity...
09.05 01:38:32 [Server] main/INFO Applying mixin: R1_18.MixinScreenHandler...
09.05 01:38:32 [Server] main/INFO Applying mixin: R1_18.MixinChunkGenerator...
09.05 01:38:32 [Server] main/INFO Applying mixin: R1_18.MixinPersistentStateManager...
09.05 01:38:32 [Server] main/INFO Applying mixin: R1_18.MixinPlayerManager...
09.05 01:38:32 [Server] main/INFO Applying mixin: R1_18.MixinHeighttmap...
09.05 01:38:32 [Server] main/INFO Applying mixin: R1_18.MixinWorld_18...
09.05 01:38:37 [Server] main/ERROR Minecraft has crashed!
09.05 01:38:37 [Server] INFO net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/kyori/adventure/audience/Audience
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
09.05 01:38:37 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
09.05 01:38:37 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:67) [fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/kyori/adventure/audience/Audience
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
09.05 01:38:37 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:342) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
09.05 01:38:37 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:342) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
09.05 01:38:37 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:342) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_1299.<clinit>(class_1299.java:161) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_3031.<clinit>(class_3031.java:81) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_6800.<clinit>(class_6800.java:19) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
09.05 01:38:37 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
09.05 01:38:37 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO ... 7 more
09.05 01:38:37 [Server] INFO Caused by: java.lang.ClassNotFoundException: class net.kyori.adventure.audience.Audience is currently restricted from being loaded
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:301) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
09.05 01:38:37 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:342) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
09.05 01:38:37 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:342) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
09.05 01:38:37 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:342) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_1299.<clinit>(class_1299.java:161) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_3031.<clinit>(class_3031.java:81) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_6800.<clinit>(class_6800.java:19) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
09.05 01:38:37 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
09.05 01:38:37 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
09.05 01:38:37 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
09.05 01:38:37 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
09.05 01:38:37 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.14.4.jar:?]
09.05 01:38:37 [Server] INFO ... 7 more`

Could someone help?

**Comment by axlecoffee** [comment]
Hello, could I please get your fabric version?

**Comment by axlecoffee** [comment]
Use Minecraft 1.18.1 with Fabric Loader 0.13.3
