### ISSUE TITLE
Error on loading, ask for help to solve

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [BukkitFabric/bukkit4fabric#349]
[08:39:37] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[08:39:37] [main/WARN]: Mod resolution failed
[08:39:37] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE cardboard 55 {depends icommon @ [*]}, ROOT_FORCELOAD_SINGLE cardboard 55]
[08:39:37] [main/INFO]: Reason: [HARD_DEP cardboard 55 {depends icommon @ [*]}, NEG_HARD_DEP ledger 1.2.4 {breaks cardboard @ [*]}]
[08:39:37] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, multiconnect-api, fabric-keybindings-v0, fabric-renderer-registries-v1, fabric-textures-v0, fabric-models-v0, fabric-screen-api-v1, fabric-rendering-v0, fabric-key-binding-api-v1, fabric-rendering-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[08:39:37] [main/INFO]: Fix: add [add:icommon 1 ([(-∞,∞)])], remove [], replace [[ledger 1.2.4, ledger 1.2.4] -> add:ledger 1 ([(-∞,∞)])]
[08:39:37] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install icommon, any version.
	 - Replace mod 'Ledger' (ledger) 1.2.4 and mod 'Ledger' (ledger) 1.2.4 with mod 'Ledger' (ledger), any version.
Unmet dependency listing:
	 - Mod 'CardboardMod' (cardboard) 55 requires any version of icommon, which is missing!
	 - Mod 'Ledger' (ledger) 1.2.4 is incompatible with any version of mod 'CardboardMod' (cardboard), but a matching version is present: 55!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]

I run cardboard on my 1.18.2 fabric server, but it doesn't work, can everyone help me to fix this?

**Comment by pisaiah** [comment]
Cardboard requires [iCommon](https://modrinth.com/mod/icommon/version/45-1.18.2)

**Comment by xiaoyueyoqwq** [comment]
> Cardboard requires [iCommon](https://modrinth.com/mod/icommon/version/45-1.18.2)

ok I got it, thanks for your support :)

**Comment by xiaoyueyoqwq** [comment]
I add ICommon in my server, but Cardboard still didn't work, This is report

**Try 'sleep --help' for more information.
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[16:46:59] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[16:47:00] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[16:47:00] [main/WARN]: Mod resolution failed
[16:47:00] [main/INFO]: Immediate reason: [NEG_HARD_DEP ledger 1.2.4 {breaks cardboard @ [*]}, NEG_HARD_DEP ledger 1.2.4 {breaks cardboard @ [*]}, ROOT_FORCELOAD cardboard, ROOT_FORCELOAD_SINGLE ledger 1.2.4]
[16:47:00] [main/INFO]: Reason: [NEG_HARD_DEP ledger 1.2.4 {breaks cardboard @ [*]}]
[16:47:00] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, multiconnect-api, fabric-keybindings-v0, fabric-renderer-registries-v1, fabric-textures-v0, fabric-models-v0, fabric-rendering-v0, fabric-screen-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[16:47:00] [main/INFO]: Fix: add [], remove [], replace [[ledger 1.2.4] -> add:ledger 1 ([(-∞,∞)])]
[16:47:00] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Replace mod 'Ledger' (ledger) 1.2.4 with any version that is compatible with:
                 - cardboard 55
Unmet dependency listing:
         - Mod 'Ledger' (ledger) 1.2.4 is incompatible with any version of mod 'CardboardMod' (cardboard), but matching versions are present: 55/55!
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.13.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.13.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.13.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]**

**Comment by someone1995** [comment]
Ledger isn't compatible with Cardboard, also why are you using 0.13.3

**Comment by xiaoyueyoqwq** [comment]
[root@localhost mcserver]# ./start.sh
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[22:18:16] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.8
[22:18:16] [ForkJoinPool-1-worker-1/WARN]: Mod com_github_wearblackallday_javautils uses the version bd58640372 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'bd58640372'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[22:18:16] [ForkJoinPool-1-worker-1/WARN]: Mod com_github_shevek_parallelgzip uses the version af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[22:18:16] [ForkJoinPool-1-worker-1/WARN]: Mod com_github_isaiahpatton_specialsource uses the version master-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'master'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[22:18:17] [main/WARN]: Mod resolution failed
[22:18:17] [main/INFO]: Immediate reason: [NEG_HARD_DEP ledger 1.2.4 {breaks cardboard @ [*]}, NEG_HARD_DEP ledger 1.2.4 {breaks cardboard @ [*]}, ROOT_FORCELOAD cardboard, ROOT_FORCELOAD_SINGLE ledger 1.2.4]
[22:18:17] [main/INFO]: Reason: [NEG_HARD_DEP ledger 1.2.4 {breaks cardboard @ [*]}]
[22:18:17] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, multiconnect-api, fabric-renderer-registries-v1, fabric-textures-v0, fabric-models-v0, fabric-screen-api-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-key-binding-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[22:18:17] [main/INFO]: Fix: add [], remove [], replace [[ledger 1.2.4] -> add:ledger 1 ([(-∞,∞)])]
[22:18:17] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Ledger' (ledger) 1.2.4 with any version that is compatible with:
		 - cardboard 55
Unmet dependency listing:
	 - Mod 'Ledger' (ledger) 1.2.4 is incompatible with any version of mod 'CardboardMod' (cardboard), but matching versions are present: 55/55!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]

_I don't understand_
