### ISSUE TITLE
Mod resolution encountered an incompatible mod set!（1.18.2）

### ISSUE THREAD

**Issue by fengziyun** [BukkitFabric/bukkit4fabric#382]
fabric version is 0.14.9

``` shell
[main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Install fabric, any version.
Unmet dependency listing:
         - Mod 'CardboardMod' (cardboard) 61 requires any version of fabric, which is missing!
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
```

**Comment by fengziyun** [comment]
``` shell
 D:\Users\User\downloads\temp\mods

2022/11/16  11:08    <DIR>          .
2022/11/16  11:08    <DIR>          ..
2022/11/16  10:47         3,221,923 Cardboard-1.18.2.jar
2022/11/16  11:08            80,128 iCommon-Fabric-1.18.2.jar
```

**Comment by fengziyun** [comment]
sorry,i not see this https://github.com/CardboardPowered/cardboard/issues/307
