### ISSUE TITLE
Mod resolution encountered an incompatible mod set!(CreateAstralServer)minecraft 1.18.2

### ISSUE THREAD

**Issue by fengziyun** [BukkitFabric/bukkit4fabric#383]
``` shell
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[11:46:30] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.9
[11:46:30] [ForkJoinPool-1-worker-18/WARN]: Mod cobblegen uses the version v1.11b36+mc1.18.x which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:46:30] [ForkJoinPool-1-worker-20/WARN]: Mod createaddition uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:46:30] [ForkJoinPool-1-worker-16/WARN]: Mod globaldataandresourcepacks uses the version 1.12.3_fabric which isn't compatible with Loader's extended semantic version format (Could not parse version number component '3_fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:46:30] [ForkJoinPool-1-worker-11/WARN]: Mod create uses the version 0.5.0e-733 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0e'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:46:30] [ForkJoinPool-1-worker-10/WARN]: Mod letmedespawn uses the version fabric-1.0.0 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:46:30] [ForkJoinPool-1-worker-15/WARN]: Mod registrate-fabric uses the version MC1.18.2-1.1.4 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'MC1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:46:30] [ForkJoinPool-1-worker-10/WARN]: Mod com_github_isaiahpatton_specialsource uses the version master-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'master'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:46:31] [main/WARN]: Mod resolution failed
[11:46:31] [main/INFO]: Immediate reason: [NEG_HARD_DEP servercore 1.2.9-1.18.2 {breaks cardboard @ [*]}, ROOT_FORCELOAD_SINGLE cardboard 61, ROOT_FORCELOAD_SINGLE servercore 1.2.9-1.18.2]
[11:46:31] [main/INFO]: Reason: [NEG_HARD_DEP servercore 1.2.9-1.18.2 {breaks cardboard @ [*]}]
[11:46:31] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, spyglass-improvements, fabric-keybindings-v0, fabric-textures-v0, indium, satin, inventoryprofilesnext, fabric-screen-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, chat_heads, puzzle, invmove, fabric-models-v0, flywheel, fabric-rendering-v0, fabric-rendering-v1, fabric-key-binding-api-v1, noindium, controlling, blanket-client-tweaks]
[11:46:31] [main/INFO]: Fix: add [], remove [], replace [[servercore 1.2.9-1.18.2] -> add:servercore 1 ([(-∞,∞)])]
[11:46:31] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Replace mod 'ServerCore' (servercore) 1.2.9-1.18.2 with any version that is compatible with:
                 - cardboard 61
Unmet dependency listing:
         - Mod 'ServerCore' (servercore) 1.2.9-1.18.2 is incompatible with any version of mod 'CardboardMod' (cardboard), but a matching version is present: 61!
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:0.11.1]
```
> mods list
``` shell

 ad-astra-1.0.2-1.18.2.jar
 aileron-1.18.2-fabric-1.0.0.jar
 alternate-current-mc1.18-1.4.0.jar
 appleskin-fabric-mc1.18.2-2.4.0.jar
 architectury-4.9.84-fabric.jar
 autoconfig1u-3.4.0.jar
 automobility-0.2.1+1.18.2.jar
 badpackets-fabric-0.1.2.jar
 balm-fabric-3.2.0+0.jar
 bettercombat-fabric-1.4.4+1.18.2.jar
'Blanket Client tweaks-1.0.4.jar'
 BOMD-1.3.8-1.18.2.jar
 c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar
 campanion-3.0.3.jar
 capybara-1.18.2-1.0.6.jar
 Cardboard-1.18.2.jar
 cardinal-components-api-4.2.0.jar
 catwalks-inc-1.3.0.jar
 cccbridge-1.3.0-fabric.jar
 cc-restitched-1.100.8.jar
 Chassis-Fabric-1.1.0.jar
 chat_heads-0.6.0-fabric-1.18.1.jar
 Chunky-1.2.164.jar
 cloth-config-6.4.90-fabric.jar
 Clumps-fabric-1.18.2-8.0.0+15.jar
 cobblegen-v1.11b36+mc1.18.x.jar
 collective-fabric-1.18.2-4.36.jar
 combatroll-fabric-1.0.8+1.18.2.jar
 completeconfig-lib-1.4.1.jar
 Compressor-Fabric-0.2.0.jar
 Controlling-fabric-1.18.2-9.0+22.jar
 createaddition+1.18.2-20220914a.jar
'CreateCrystalClear-1.0-fabric port.jar'
 createdeco-1.2.9-github-fabric-fork.jar
 create-fabric-1.18.2-0.5.0e-733.jar
 doodads-0.1.2-github-fork.jar
'drinkbeer-v3.0.2 for 1.18.1.jar'
 dustrial-decor-fabric-0.5.jar
 environmentalcreepers-fabric-1.18.0-1.6.0.jar
 expanded-trident-enchanting-1.0.3.jar
 fabric-api-0.66.0+1.18.2.jar
 fabric-carpet-1.18.2-1.4.69+v220331.jar
 fabric-language-kotlin-1.8.3+kotlin.1.7.10.jar
 farmers-delight-fabric-1.18.2-1.2.2.jar
 ferritecore-4.2.1-fabric.jar
 ForgeConfigAPIPort-v3.2.4-1.18.2-Fabric.jar
 ftb-library-fabric-1802.3.6-build.140.jar
 ftb-quests-fabric-1802.3.8-build.106.jar
 ftb-teams-fabric-1802.2.6-build.51.jar
 geckolib-fabric-1.18-3.0.62.jar
 global_packs-fabric-1.18.2-1.12.3_fabric.jar
 harvestwithease-1.18.2-4.0.0.0-fabric.jar
 Hephaestus-1.18.2-3.5.2.150.jar
 Iceberg-1.18.2-fabric-1.0.38.jar
 iCommon-Fabric-1.18.2.jar
 idwtialsimmoedm-0.1.1+1.18.jar
 indium-1.0.7+mc1.18.2.jar
 indrev-1.14.0-BETA.jar
 InventoryProfilesNext-fabric-1.18.2-1.6.3.jar
 InvMove-1.18-0.7.0-Fabric.jar
 item-filters-fabric-1802.2.7-build.33.jar
 krypton-0.1.9.jar
 kubejs-create-fabric-1802.2.2-build.26.jar
 kubejs-fabric-1802.5.4-build.533.jar
 lanterns-belong-on-walls-1.3.0-1.18.x.jar
 lazydfu-0.1.2.jar
 letmedespawn-fabric-1.0.0.jar
 limitedchunks.fabric-1.18.2-2.5.jar
 lithium-fabric-mc1.18.2-0.7.10.jar
 mcdw-5.0.2-1.18.jar
 memoryleakfix-1.18.2-0.7.0.jar
 midnightlib-0.4.4.jar
 naturalist-fabric-1.1.0-1.18.2.jar
 notenoughcrashes-4.1.6+1.18.2-fabric.jar
 packages-fabric-1.18.2-3.jar
 packed-inventory-0.2.2+1.18.2.jar
 Patchouli-1.18.2-71.1-FABRIC.jar
 phonos-0.3+1.18.2.jar
 player-animation-lib-fabric-0.3.5.jar
 polaroidcamera-1.2.9.jar
 probablychests-0.5.4-1.18.2.jar
 projectiledamage-1.0.7.jar
 puzzle-1.4.0-1.18.jar
 PuzzlesLib-v3.3.5-1.18.2-Fabric.jar
 questsadditions-fabric-1.18.2-1.4.0.jar
 rhino-fabric-1802.1.14-build.225.jar
 RoughlyEnoughItems-8.3.529.jar
 scout-1.18.2-1.1.1.jar
 servercore-1.2.9-1.18.2.jar
 spark-1.9.1-fabric.jar
 spyglass-improvements-1.2+mc1.18.2+fabric.jar
 starlight-1.0.2+fabric.89b8d9f.jar
 starterkit-fabric_1.18.2-3.5.jar
 structures_compass-fabric-1.18.2-1.4.2.jar
 suggestion-tweaker-1.18.2-1.3.0-fabric.jar
'[TEST]Incendium_v5.0.4.jar'
'[TEST]LibraryFerret-Fabric-1.18.2-2.0.0.jar'
 toms_storage_fabric-1.18.2-1.4.3.jar
 Towns-and-Towers-1.18.2-1.6.0.jar
 trinkets-3.3.1.jar
 villainousdifficultymultipliers-1.1.2-1.18.jar
 wthit-fabric-4.13.1.jar
 yippee-1.0.0-fabric.jar
 youre-in-grave-danger-1.3.10.jar
 YungsApi-1.18.2-Fabric-2.0.8.jar

```
have `Cardboard-1.18.2.jar` `iCommon-Fabric-1.18.2.jar` `fabric-api-0.66.0+1.18.2.jar`

**Comment by fengziyun** [comment]
`mv Cardboard-1.18.2.jar Cardboard-1.18.2.jar.bak`
start server

```shell
 java -jar server.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[11:56:13] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.9
[11:56:13] [ForkJoinPool-1-worker-3/WARN]: Mod cobblegen uses the version v1.11b36+mc1.18.x which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:56:13] [ForkJoinPool-1-worker-17/WARN]: Mod globaldataandresourcepacks uses the version 1.12.3_fabric which isn't compatible with Loader's extended semantic version format (Could not parse version number component '3_fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:56:13] [ForkJoinPool-1-worker-5/WARN]: Mod letmedespawn uses the version fabric-1.0.0 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:56:13] [ForkJoinPool-1-worker-14/WARN]: Mod createaddition uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:56:13] [ForkJoinPool-1-worker-23/WARN]: Mod create uses the version 0.5.0e-733 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0e'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:56:13] [ForkJoinPool-1-worker-7/WARN]: Mod registrate-fabric uses the version MC1.18.2-1.1.4 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'MC1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:56:13] [main/INFO]: Loading 196 mods:
        - ad_astra 1.0.2
        - advanced_runtime_resource_pack 0.5.7 via phonos
        - aileron 1.0.0
        - alternate-current 1.4.0
        - appleskin 2.4.0+mc1.18.2
        - architectury 4.9.84
        - autoconfig1u 3.4.0
        - automobility 0.2.1+1.18.2
        - badpackets 0.1.2
        - balm-fabric 3.2.0+0
        - bettercombat 1.4.4+1.18.2
        - blue_endless_jankson 1.2.1 via jankson
        - bosses_of_mass_destruction 1.3.8-1.18.2
        - c2me 0.2.0+alpha.7.0
        - campanion 3.0.3
        - capybara 1.0.6
        - cardinal-components 4.2.0
        - cardinal-components-base 4.2.0 via cardinal-components
        - cardinal-components-block 4.2.0 via cardinal-components
        - cardinal-components-chunk 4.2.0 via cardinal-components
        - cardinal-components-entity 4.2.0 via cardinal-components
        - cardinal-components-item 4.2.0 via cardinal-components
        - cardinal-components-level 4.2.0 via cardinal-components
        - cardinal-components-scoreboard 4.2.0 via cardinal-components
        - cardinal-components-world 4.2.0 via cardinal-components
        - carpet 1.4.69
        - catwalksinc 1.3.0
        - cccbridge 1.3.0
        - chassis 1.1.0
        - chunky 1.2.164
        - cloth-basic-math 0.6.1 via cloth-config
        - cloth-config 6.4.90
        - cloth-utils-v1 2.0.54 via computercraft
        - clumps 8.0.0+15
        - cobblegen v1.11b36+mc1.18.x
        - collective-fabric 4.36
        - com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
        - com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
        - com_eliotlash_mclib_mclib 18 via geckolib3
        - com_eliotlash_molang_molang 19 via geckolib3
        - com_github_llamalad7_mixinextras 0.0.11 via porting_lib
        - com_google_code_findbugs_jsr305 3.0.2 via create
        - com_ishland_c2me_libs_ 0.2.0+alpha.7.0 via c2me
        - com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
        - combatroll 1.0.8+1.18.2
        - completeconfig 1.4.1
        - compressor 0.2.0
        - computercraft 1.100.8
        - create 0.5.0e-733
        - create_crystal_clear 1.0-fabric-patch1
        - createaddition ${version}
        - createdeco 1.2.9-1.18.2
        - crowdin-translate 1.4+1.18.2 via compressor
        - doodads 0.1.2-1.18.2
        - drinkbeer 3.0.2
        - dripstone_fluid_lib 1.2.0 via milk
        - dustrial_decor 0.5
        - enchant_giver 1.2.1 via mcdw
        - environmentalcreepers 1.6.0
        - error_notifier 1.0.9 via roughlyenoughitems
        - expanded_trident_enchanting 1.0.3
        - fabric-api 0.66.0+1.18.2
        - fabric-api-base 0.4.4+d7c144a860 via fabric-api
        - fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric-api
        - fabric-biome-api-v1 8.0.6+651bcc5960 via fabric-api
        - fabric-block-api-v1 1.0.0+ee3621fc60 via fabric-api
        - fabric-command-api-v1 1.1.9+d7c144a860 via fabric-api
        - fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric-api
        - fabric-containers-v0 0.1.23+d7c144a860 via fabric-api
        - fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric-api
        - fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric-api
        - fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric-api
        - fabric-data-generation-api-v1 3.0.2+9fcb91d260 via fabric-api
        - fabric-dimensions-v1 2.1.20+489d6f8260 via fabric-api
        - fabric-entity-events-v1 1.4.8+d7c144a860 via fabric-api
        - fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric-api
        - fabric-events-lifecycle-v0 0.2.19+d7c144a860 via fabric-api
        - fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric-api
        - fabric-item-api-v1 1.5.2+17cbbd4360 via fabric-api
        - fabric-item-groups-v0 0.3.14+91896a4960 via fabric-api
        - fabric-language-kotlin 1.8.3+kotlin.1.7.10
        - fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric-api
        - fabric-loot-api-v2 1.1.0+1997ad1260 via fabric-api
        - fabric-loot-tables-v1 1.1.2+e747827960 via fabric-api
        - fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric-api
        - fabric-networking-api-v1 1.0.23+2d30af4b60 via fabric-api
        - fabric-networking-v0 0.3.10+b4f4f6cd60 via fabric-api
        - fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric-api
        - fabric-particles-v1 0.2.12+526dc1ac60 via fabric-api
        - fabric-permissions-api-v0 0.1-SNAPSHOT via servercore
        - fabric-registry-sync-v0 0.9.11+bb2e047760 via fabric-api
        - fabric-rendering-data-attachment-v1 0.3.8+ee3621fc60 via fabric-api
        - fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric-api
        - fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric-api
        - fabric-resource-loader-v0 0.5.2+446e059560 via fabric-api
        - fabric-screen-handler-api-v1 1.2.2+1f6558e860 via fabric-api
        - fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric-api
        - fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric-api
        - fabricloader 0.14.9
        - fake-player-api 0.3.0 via create
        - farmersdelight 1.18.2-1.2.2
        - ferritecore 4.2.1
        - fiber 0.23.0-2 via collective-fabric
        - forge_tags 2.1 via create
        - forgeconfigapiport 3.2.4
        - ftblibrary 1802.3.6-build.140
        - ftbquests 1802.3.8-build.106
        - ftbteams 1802.2.6-build.51
        - geckolib3 3.0.62
        - globaldataandresourcepacks 1.12.3_fabric
        - harvestwithease 4.0.0.0
        - iceberg 1.0.38
        - icommon 1.18
        - idwtialsimmoedm 0.1.1+1.18
        - incendium 5.0.4
        - indrev 1.14.0-BETA
        - itemfilters 1802.2.7-build.33
        - jankson 4.0.0+j1.2.0 via libgui
        - java 17
        - jsonem 0.1.2 via automobility
        - krypton 0.1.9
        - kubejs 1802.5.4-build.533
        - kubejs_create 1802.2.2-build.26
        - lazydfu 0.1.2
        - letmedespawn fabric-1.0.0
        - libblockattributes_core 0.10.0 via indrev
        - libblockattributes_fluids 0.10.0 via indrev
        - libblockattributes_items 0.10.0 via indrev
        - libgui 5.3.2+1.18.2 via indrev
        - libninepatch 1.1.0 via libgui
        - libraryferret 2.0.0
        - limitedchunks 1.18.2-2.5
        - lithium 0.7.10
        - maelstrom_library 1.2.4-1.18.2 via bosses_of_mass_destruction
        - magna 1.7.0-1.18-pre1 via indrev
        - mantle 1.18.2-1.9.156 via tconstruct
        - mcdw 5.0.2-1.18
        - memoryleakfix 1.18.2-0.7.0
        - midnightlib 0.4.4
        - milk 0.3.2 via create
        - minecraft 1.18.2
        - mm 2.3 via porting_lib
        - multipart_entities 1.1.5-1.18.2 via bosses_of_mass_destruction
        - myron 1.6.3+1.18.1 via automobility
        - naturalist 1.1.0
        - notenoughcrashes 4.1.6+1.18.2
        - omega-config 1.2.3-1.18.1 via cobblegen
        - org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
        - org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
        - org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
        - org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
        - org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin
        - packages 3
        - packed-inventory 0.2.2+1.18.2
        - patchouli 1.18.2-71.1-FABRIC
        - phonos 0.3+1.18.2
        - placeholder-api 1.1.3+1.17.1 via servercore
        - player-animator 0.3.5
        - polaroidcamera 1.2.9
        - porting_lib 1.2.550-beta+1.18.2-stable via tconstruct
        - probablychests 0.5.4-1.18.2
        - projectiledamage 1.0.7
        - puzzleslib 3.3.5
        - questsadditions 1.4.0
        - reach-entity-attributes 2.2.0 via mcdw
        - registrate-fabric MC1.18.2-1.1.4 via create
        - rhino 1802.1.14-build.225
        - roughlyenoughitems 8.3.529
        - scout 1.1.1
        - seedfix 1.0.2 via incendium
        - serialization_hooks 0.3.23 via tconstruct
        - servercore 1.2.9-1.18.2
        - spark 1.9.1
        - star 1.3+1.18.2 via mantle
        - starlight 1.0.2+fabric.89b8d9f
        - starterkit-fabric 3.5
        - step-height-entity-attribute 1.0.0 via indrev
        - structures_compass 1.18.2-1.4.2
        - suggestion_tweaker 1.18.2-1.3.0
        - t_and_t 1.6
        - tconstruct 1.18.2-3.5.2.150
        - team_reborn_energy 2.2.0 via ad_astra
        - toms_storage 1.4.3
        - trinkets 3.3.1
        - vdm 1.1.2-1.18
        - walllanterns 1.3.0-1.18.x
        - wthit 4.13.1
        - yigd 1.3.10
        - yippee 1.0.0
        - yungsapi 1.18.2-Fabric-2.0.8
[11:56:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/opt/mcsmanager/daemon/data/InstanceData/faa7c7d9c94e4005adc07f9fd7f38e70/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[11:56:14] [main/INFO]: Compatibility level set to JAVA_17
[11:56:15] [main/WARN]: Reference map 'aileron-fabric-refmap.json' for aileron.mixins.json could not be read. If this is a development environment you can ignore this message
[11:56:15] [main/INFO]: Configuration loaded successfully after 289.52261ms
[11:56:15] [main/INFO]: Successfully loaded configuration for C2ME
[11:56:15] [main/INFO]: Initializing C2ME Compatibility Module
[11:56:15] [main/WARN]: Reference map 'cccbridge-refmap.json' for cccbridge.mixins.json could not be read. If this is a development environment you can ignore this message
[11:56:15] [main/INFO]: Loaded configuration file for Lithium: 102 options available, 3 override(s) found
[11:56:16] [main/WARN]: Reference map 'structures_compass-fabric-refmap.json' for structures_compass.mixins.json could not be read. If this is a development environment you can ignore this message
[11:56:16] [main/WARN]: Reference map 'yippee-refmap.json' for yippee.mixins.json could not be read. If this is a development environment you can ignore this message
[11:56:16] [main/WARN]: Error loading class: net/minecraft/class_572 (java.lang.ClassNotFoundException: net/minecraft/class_572)
[11:56:16] [main/WARN]: @Mixin target net.minecraft.class_572 was not found porting_lib.mixins.common.json:accessor.HumanoidModelAccessor from mod porting_lib
[11:56:17] [main/WARN]: Error loading class: net/minecraft/class_304 (java.lang.ClassNotFoundException: net/minecraft/class_304)
[11:56:17] [main/WARN]: @Mixin target net.minecraft.class_304 was not found ftblibrary-fabric.mixins.json:KeyMappingAccessor from mod ftblibrary
[11:56:17] [main/INFO]: =======================================================
[11:56:17] [main/INFO]:  iCommon - Isaiah's common library for mods.
[11:56:17] [main/INFO]:  Copyright (c) 2018-2021 by Isaiah. Running on MC 1.18.2
[11:56:17] [main/INFO]: =======================================================
[11:56:17] [main/INFO]: Applying mixin: MixinMinecraftServer...
[11:56:17] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[11:56:17] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
[11:56:18] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [c2me, krypton]) disables it and children
[11:56:18] [main/WARN]: Error loading class: net/minecraft/class_312 (java.lang.ClassNotFoundException: net/minecraft/class_312)
[11:56:18] [main/WARN]: @Mixin target net.minecraft.class_312 was not found polaroidcamera.mixins.json:MouseMixin from mod polaroidcamera
[11:56:18] [main/WARN]: Error loading class: net/minecraft/class_5616 (java.lang.ClassNotFoundException: net/minecraft/class_5616)
[11:56:18] [main/WARN]: @Mixin target net.minecraft.class_5616 was not found registrate-fabric.mixins.json:accessor.BlockEntityRenderersAccessor from mod registrate-fabric
[11:56:18] [main/WARN]: Error loading class: net/minecraft/class_1092 (java.lang.ClassNotFoundException: net/minecraft/class_1092)
[11:56:18] [main/WARN]: @Mixin target net.minecraft.class_1092 was not found star.mixins.json:client.BakedModelManagerMixin from mod star
[11:56:18] [main/WARN]: Error loading class: net/minecraft/class_746 (java.lang.ClassNotFoundException: net/minecraft/class_746)
[11:56:18] [main/WARN]: @Mixin target net.minecraft.class_746 was not found star.mixins.json:client.ClientPlayerEntityMixin from mod star
[11:56:18] [main/WARN]: Error loading class: net/minecraft/class_1059 (java.lang.ClassNotFoundException: net/minecraft/class_1059)
[11:56:18] [main/WARN]: @Mixin target net.minecraft.class_1059 was not found star.mixins.json:client.SpriteAtlasTextureMixin from mod star
[11:56:18] [main/WARN]: Error loading class: net/minecraft/class_746 (java.lang.ClassNotFoundException: net/minecraft/class_746)
[11:56:18] [main/WARN]: @Mixin target net.minecraft.class_746 was not found vdm.mixins.json:LocalChatMixin from mod vdm
[11:56:18] [main/INFO]: Adding mixins: [None]
[11:56:18] [main/INFO]: Applying mixin: R1_18.MixinEntity...
[11:56:18] [main/INFO]: Applying mixin: R1_18.MixinPlayer...
[11:56:18] [main/INFO]: Applying mixin: R1_18.MixinBlockEntity...
[11:56:18] [main/INFO]: Applying mixin: R1_18.MixinChestBlockEntity...
[11:56:18] [main/INFO]: Applying mixin: R1_18.MixinCampfireBlockEntity...
[11:56:18] [main/INFO]: Applying mixin: R1_18.MixinScreenHandler...
[11:56:18] [main/INFO]: Applying mixin: R1_18.MixinChunkGenerator...
[11:56:18] [main/INFO]: Applying mixin: R1_18.MixinPersistentStateManager...
[11:56:18] [main/INFO]: Applying mixin: R1_18.MixinPlayerManager...
[11:56:18] [main/INFO]: Applying mixin: R1_18.MixinHeighttmap...
[11:56:18] [main/INFO]: Applying mixin: R1_18.MixinWorld_18...
[11:56:19] [main/INFO]: I used the json to destroy the json...........
```

**Comment by fengziyun** [comment]
If you can change the loading sequence, it should start smoothly

**Comment by TSDman** [comment]
> If you can change the loading sequence, it should start smoothly

How do you change the loading sequence? I am having the same problem and I can't seem to be able to fix it.

**Comment by fengziyun** [comment]
很抱歉，我并不能解决这个问题。因为我本身不是开发人员，对编程就只会python的冰山一角。我能搞清楚问题出在哪里，但是缺无法去解决这个问题。很抱歉无法给你一个解决方案。

Sorry, I can't solve this problem. Because I am not a developer myself, I only know the tip of the iceberg of python about programming. I can figure out where the problem is, but I can't solve it. I'm sorry I can't give you a solution.&nbsp; --&nbsp;This translation is machine translation
&nbsp;


dogeziyun
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月4日(星期六) 下午4:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CardboardPowered/cardboard] Mod resolution encountered an incompatible mod set!(CreateAstralServer)minecraft 1.18.2 (Issue #383)






如果你能改变加载顺序，它应该能顺利启动。

你如何改变加载顺序？我也有同样的问题而我却似乎无法挽回。

—
直接回复此邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.
