### ISSUE TITLE
can't download libs

### ISSUE THREAD

**Issue by jerrytu12345** [BukkitFabric/bukkit4fabric#385]
hello IsaiahPatton
i am a chinese user and i tried to download all libs on your github
but the server still dont work
then i tried to fix
but still, dont work
here is the logs:
D:\testserver>C:\MCLDownload\ext\jre-v64-220420\jdk17\bin\java.exe -Xmx2G -jar fabric-server-launch.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[14:38:40] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.14.9
[14:38:40] [ForkJoinPool-1-worker-2/WARN]: Mod cardboard uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:38:40] [ForkJoinPool-1-worker-2/WARN]: Mod com_github_isaiahpatton_specialsource uses the version master-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'master'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:38:40] [main/INFO]: Loading 41 mods:
        - cardboard ${version}
        - com_github_isaiahpatton_specialsource master-SNAPSHOT via cardboard
        - fabric 0.46.1+1.18
        - fabric-api-base 0.4.1+b4f4f6cd65 via fabric
        - fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
        - fabric-biome-api-v1 6.0.1+ded849a965 via fabric
        - fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
        - fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
        - fabric-containers-v0 0.1.18+d154e2c665 via fabric
        - fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
        - fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
        - fabric-dimensions-v1 2.1.9+a1d9bbf565 via fabric
        - fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
        - fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
        - fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
        - fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
        - fabric-item-api-v1 1.3.0+691a79b565 via fabric
        - fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
        - fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
        - fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
        - fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
        - fabric-mining-levels-v0 0.1.8+b4f4f6cd65 via fabric
        - fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
        - fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
        - fabric-object-builder-api-v1 1.11.1+3b82842e65 via fabric
        - fabric-object-builders-v0 0.7.9+3ac43d9565 via fabric
        - fabric-particles-v1 0.2.9+526dc1ac65 via fabric
        - fabric-registry-sync-v0 0.9.0+befed49e65 via fabric
        - fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
        - fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
        - fabric-resource-conditions-api-v1 1.0.1+13eda06565 via fabric
        - fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
        - fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
        - fabric-structure-api-v1 2.1.0+0a73a6c265 via fabric
        - fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
        - fabric-tool-attribute-api-v1 1.3.5+fb3b57b465 via fabric
        - fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
        - fabricloader 0.14.9
        - icommon 1.18
        - java 17
        - minecraft 1.18.1
[14:38:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/testserver/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[14:38:41] [main/INFO]: Compatibility level set to JAVA_16
[14:38:41] [main/INFO]: Loading Libraries...
[14:38:41] [main/INFO]: Debug: Loading library paper-api-1.17-dev.jar
[14:38:41] [main/INFO]: Debug: Loading library sqlite-jdbc-3.21.0.1.jar
[14:38:41] [main/INFO]: Debug: Loading library mysql-connector-java-5.1.46.jar
[14:38:41] [main/INFO]: Debug: Loading library commons-lang-2.6.jar
[14:38:41] [main/INFO]: Debug: Loading library commons-collections4-4.4.jar
[14:38:41] [main/INFO]: Debug: Loading library commons-collections-3.2.1.jar
[14:38:41] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71) ~[fabric-loader-0.14.9.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.server.Main failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.9.jar:?]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/configuration/file/FileConfiguration
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.cardboardpowered.mixin.CardboardMixinPlugin.shouldApplyMixin(CardboardMixinPlugin.java:145) ~[Cardboard-1.17-1.18-b50.jar:?]
        at org.spongepowered.asm.mixin.transformer.PluginHandle.shouldApplyMixin(PluginHandle.java:132) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.shouldApplyMixin(MixinInfo.java:988) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:953) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.9.jar:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.configuration.file.FileConfiguration
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.cardboardpowered.mixin.CardboardMixinPlugin.shouldApplyMixin(CardboardMixinPlugin.java:145) ~[Cardboard-1.17-1.18-b50.jar:?]
        at org.spongepowered.asm.mixin.transformer.PluginHandle.shouldApplyMixin(PluginHandle.java:132) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.shouldApplyMixin(MixinInfo.java:988) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:953) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.9.jar:?]

**Comment by jerrytu12345** [comment]
[latest.log](https://github.com/CardboardPowered/cardboard/files/10199359/latest.log)

**Comment by jerrytu12345** [comment]
i think is the problem of fabric loader
could u tell me which fabric loader shoud i use

**Comment by wdog5** [comment]
it decided by you network
