### ISSUE TITLE
Crashing with only Lithium, Fabric API, iCommon, and Cardboard installed

### ISSUE THREAD

**Issue by TheAlphaWolf449** [BukkitFabric/bukkit4fabric#396]
Not sure why its crashing, its some kind of mixin issue
I have 1.18.2 version of the 4 mods.

Here is a log:
[22:36:46] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.18
[22:36:46] [ForkJoinPool-1-worker-4/WARN]: Mod com_github_isaiahpatton_specialsource uses the version master-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'master'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[22:36:47] [main/INFO]: Loading 42 mods:
	- cardboard 55
	   \-- com_github_isaiahpatton_specialsource master-SNAPSHOT
	- fabric-api 0.76.0+1.18.2
	   |-- fabric-api-base 0.4.5+64b7c69360
	   |-- fabric-api-lookup-api-v1 1.6.3+2373a54560
	   |-- fabric-biome-api-v1 8.0.7+e83becad60
	   |-- fabric-block-api-v1 1.0.0+ee3621fc60
	   |-- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560
	   |-- fabric-command-api-v1 1.1.10+d7c144a860
	   |-- fabric-commands-v0 0.2.9+b4f4f6cd60
	   |-- fabric-containers-v0 0.1.24+d7c144a860
	   |-- fabric-content-registries-v0 3.1.3+c85f2e3860
	   |-- fabric-convention-tags-v1 1.1.0+43ce63a460
	   |-- fabric-crash-report-info-v1 0.2.1+ee261a3e60
	   |-- fabric-data-generation-api-v1 3.1.0+6c70b68e60
	   |-- fabric-dimensions-v1 2.1.21+489d6f8260
	   |-- fabric-entity-events-v1 1.4.9+d7c144a860
	   |-- fabric-events-interaction-v0 0.4.20+d7c144a860
	   |-- fabric-events-lifecycle-v0 0.2.22+d7c144a860
	   |-- fabric-game-rule-api-v1 1.0.13+d7c144a860
	   |-- fabric-item-api-v1 1.6.2+8165403660
	   |-- fabric-item-groups-v0 0.3.16+91896a4960
	   |-- fabric-key-binding-api-v1 1.0.12+54e5b2ec60
	   |-- fabric-keybindings-v0 0.2.10+b4f4f6cd60
	   |-- fabric-lifecycle-events-v1 2.1.1+cc71601c60
	   |-- fabric-loot-api-v2 1.1.2+1997ad1260
	   |-- fabric-loot-tables-v1 1.1.4+e747827960
	   |-- fabric-mining-level-api-v1 2.1.6+cc71601c60
	   |-- fabric-models-v0 0.3.7+d7c144a860
	   |-- fabric-networking-api-v1 1.0.24+2d30af4b60
	   |-- fabric-networking-v0 0.3.11+b4f4f6cd60
	   |-- fabric-object-builder-api-v1 2.1.5+032c981d60
	   |-- fabric-particles-v1 0.2.13+526dc1ac60
	   |-- fabric-registry-sync-v0 0.9.12+bb2e047760
	   |-- fabric-renderer-api-v1 0.5.0+bf48649860
	   |-- fabric-renderer-indigo 0.6.1+03e2b68760
	   |-- fabric-renderer-registries-v1 3.2.12+b4f4f6cd60
	   |-- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60
	   |-- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60
	   |-- fabric-rendering-v0 1.1.14+b4f4f6cd60
	   |-- fabric-rendering-v1 1.10.8+54e5b2ec60
	   |-- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660
	   |-- fabric-resource-loader-v0 0.5.3+047a5ecb60
	   |-- fabric-screen-api-v1 1.0.11+d882b91560
	   |-- fabric-screen-handler-api-v1 1.2.3+1f6558e860
	   |-- fabric-textures-v0 1.0.13+3ac43d9560
	   |-- fabric-transfer-api-v1 1.6.4+f4563ac860
	   \-- fabric-transitive-access-wideners-v1 1.1.0+e747827960
	- fabricloader 0.14.18
	- icommon 1.18
	- java 17
	- lithium 0.10.3
	- minecraft 1.18.2
[22:36:47] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/minecraft/multicraft/servers/server1812199/default/jar/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[22:36:47] [main/INFO]: Compatibility level set to JAVA_16
[22:36:47] [main/INFO]: Compatibility level set to JAVA_17
[22:36:47] [main/INFO]: Please wait, Scanning plugins for events...
[22:36:47] [main/INFO]: Found: 0 (Took: 0ms)
[22:36:47] [main/INFO]: Loading Libraries...
[22:36:47] [main/INFO]: Debug: Loading library paper-api-1.17-dev.jar
[22:36:47] [main/INFO]: Debug: Loading library sqlite-jdbc-3.21.0.1.jar
[22:36:47] [main/INFO]: Debug: Loading library mysql-connector-java-5.1.46.jar
[22:36:47] [main/INFO]: Debug: Loading library commons-lang-2.6.jar
[22:36:47] [main/INFO]: Debug: Loading library commons-collections4-4.4.jar
[22:36:47] [main/INFO]: Debug: Loading library commons-collections-3.2.1.jar
[22:36:47] [main/INFO]: Loaded configuration file for Lithium: 105 options available, 0 override(s) found
[22:36:47] [main/INFO]: =======================================================
[22:36:47] [main/INFO]:  iCommon - Isaiah's common library for mods.
[22:36:47] [main/INFO]:  Copyright (c) 2018-2021 by Isaiah. Running on MC 1.18.2
[22:36:47] [main/INFO]: =======================================================
[22:36:47] [main/INFO]: Applying mixin: MixinMinecraftServer...
[22:36:47] [main/INFO]: Applying mixin: R1_18.MixinEntity...
[22:36:47] [main/INFO]: Applying mixin: R1_18.MixinPlayer...
[22:36:47] [main/INFO]: Applying mixin: R1_18.MixinBlockEntity...
[22:36:47] [main/INFO]: Applying mixin: R1_18.MixinChestBlockEntity...
[22:36:47] [main/INFO]: Applying mixin: R1_18.MixinCampfireBlockEntity...
[22:36:47] [main/INFO]: Applying mixin: R1_18.MixinScreenHandler...
[22:36:47] [main/INFO]: Applying mixin: R1_18.MixinChunkGenerator...
[22:36:47] [main/INFO]: Applying mixin: R1_18.MixinPersistentStateManager...
[22:36:47] [main/INFO]: Applying mixin: R1_18.MixinPlayerManager...
[22:36:47] [main/INFO]: Applying mixin: R1_18.MixinHeighttmap...
[22:36:47] [main/INFO]: Applying mixin: R1_18.MixinWorld_18...
[22:36:49] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_3924::method_31666(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_3924;)V has incompatible changes at opcode 109 in callback lithium.mixins.json:world.block_entity_ticking.sleeping.campfire.CampfireBlockEntityMixin from mod lithium->@Inject::trySleepLit(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_3924;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Z)V.
 Expected: [Z]
    Found: [Lme/isaiah/common/R117/ICampfireBlockEntity;]
Available: [Lme/isaiah/common/R117/ICampfireBlockEntity;, I, Lnet/minecraft/class_1799;, Lnet/minecraft/class_1277;, Lnet/minecraft/class_1799;, Lnet/minecraft/class_2338;, Lme/isaiah/common/event/entity/CampfireBlockEntityCookEvent;]
[22:36:49] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:464) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.18.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3924 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.18.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:804) ~[server-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.18.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:804) ~[server-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_3924::method_31666(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_3924;)V has incompatible changes at opcode 109 in callback lithium.mixins.json:world.block_entity_ticking.sleeping.campfire.CampfireBlockEntityMixin from mod lithium->@Inject::trySleepLit(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_3924;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Z)V.
 Expected: [Z]
    Found: [Lme/isaiah/common/R117/ICampfireBlockEntity;]
Available: [Lme/isaiah/common/R117/ICampfireBlockEntity;, I, Lnet/minecraft/class_1799;, Lnet/minecraft/class_1277;, Lnet/minecraft/class_1799;, Lnet/minecraft/class_2338;, Lme/isaiah/common/event/entity/CampfireBlockEntityCookEvent;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:547) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.18.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:804) ~[server-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	... 3 more

**Comment by grabartley** [comment]
I am having the same issue, can someone please take a look?

**Comment by grabartley** [comment]
@TheAlphaWolf449 as a workaround in the meantime, I managed to get my server to start by adding the following to `lithium.properties`:

```
mixin.world.block_entity_ticking.sleeping.campfire=false
mixin.world.block_entity_ticking.sleeping.campfire.lit=false
mixin.world.block_entity_ticking.sleeping.campfire.unlit=false
```

**Comment by Mrgaton** [comment]
I am having the same issue, can someone please take a look?

**Comment by Mrgaton** [comment]
> @TheAlphaWolf449 as a workaround in the meantime, I managed to get my server to start by adding the following to `lithium.properties`:
> 
> ```
> mixin.world.block_entity_ticking.sleeping.campfire=false
> mixin.world.block_entity_ticking.sleeping.campfire.lit=false
> mixin.world.block_entity_ticking.sleeping.campfire.unlit=false
> ```

Thath worked too

**Comment by Metaloul** [comment]
> > @TheAlphaWolf449 as a workaround in the meantime, I managed to get my server to start by adding the following to `lithium.properties`:
> > ```
> > mixin.world.block_entity_ticking.sleeping.campfire=false
> > mixin.world.block_entity_ticking.sleeping.campfire.lit=false
> > mixin.world.block_entity_ticking.sleeping.campfire.unlit=false
> > ```
> 
> Thath worked too

Didn't worked for me :/
