### ISSUE TITLE
World edit 1.19.2 fabric

### ISSUE THREAD

**Issue by BingusBongusthe2nd** [BukkitFabric/bukkit4fabric#413]
When trying to use world edit, I did .//set stone, and was met with this error. I don't know what to do from here, but it mentions minekea, which is a mod we do have installed. 

This is the full error message-

An unexpected error while handling a WorldEdit command

java.lang.IllegalArgumentException: Could not parse data: minekea:redstone/pressure_plates/black_woolminecraft:stone

at org.bukkit.craftbukkit.block.data.CraftBlockData.createNewData(CraftBlockData.java:532) ~[Cardboard-1.19.2.jar:?]

at org.bukkit.craftbukkit.block.data.CraftBlockData.lambda$newData$0(CraftBlockData.java:512) ~[Cardboard-1.19.2.jar:?]

at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]

at org.bukkit.craftbukkit.block.data.CraftBlockData.newData(CraftBlockData.java:512) ~[Cardboard-1.19.2.jar:?]

at org.bukkit.craftbukkit.CraftServer.createBlockData(CraftServer.java:630) ~[Cardboard-1.19.2.jar:?]

at org.bukkit.craftbukkit.CraftServer.createBlockData(CraftServer.java:612) ~[Cardboard-1.19.2.jar:?]

at org.bukkit.Bukkit.createBlockData(Bukkit.java:2060) ~[paper-api-1.18.2-167.jar:?]

at org.bukkit.Material.createBlockData(Material.java:4096) ~[paper-api-1.18.2-167.jar:?]

at com.sk89q.worldedit.bukkit.WorldEditPlugin.lambda$initializeRegistries$0(WorldEditPlugin.java:227) ~[?:?]

at com.sk89q.worldedit.world.block.BlockType.computeDefaultState(BlockType.java:85) ~[?:?]

at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[?:?]

at com.sk89q.worldedit.world.block.BlockType.getDefaultState(BlockType.java:162) ~[?:?]

at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:354) ~[?:?]

at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:101) ~[?:?]

at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:63) ~[?:?]

at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]

at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:43) ~[?:?]

at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:30) ~[?:?]

at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]

at com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:126) ~[?:?]

at org.enginehub.piston.impl.CommandParser.lambda$isAcceptedByTypeParsers$7(CommandParser.java:497) ~[?:?]

at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]

at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]

at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]

at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]

at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]

at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]

at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]

at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]

at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]

at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]

at org.enginehub.piston.impl.CommandParser.isAcceptedByTypeParsers(CommandParser.java:492) ~[?:?]

at org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:429) ~[?:?]

at org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340) ~[?:?]

at org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240) ~[?:?]

at org.enginehub.piston.CommandManager.execute(CommandManager.java:154) ~[?:?]

at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]

at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]

at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]

at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]

at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]

at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]

at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-167.jar:?]

at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:924) ~[Cardboard-1.19.2.jar:?]

at org.cardboardpowered.impl.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:61) ~[Cardboard-1.19.2.jar:?]

at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]

at net.minecraft.class_2170.redirect$zdl000$performCommand(class_2170.java:545) ~[server-intermediary.jar:?]

at net.minecraft.class_2170.method_9249(class_2170.java:271) ~[server-intermediary.jar:?]

at net.minecraft.class_3244.method_45010(class_3244.java:3268) ~[server-intermediary.jar:?]

at net.minecraft.class_3244.method_44356(class_3244.java:1320) ~[server-intermediary.jar:?]

at net.minecraft.class_1255.method_5386(class_1255.java:68) ~[server-intermediary.jar:?]

at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]

at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]

at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]

at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]

at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]

at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]

at java.lang.Thread.run(Thread.java:833) [?:?]

Suppressed: java.lang.IllegalArgumentException: Could not parse data: minekea:redstone/pressure_plates/black_woolminecraft:stone

at org.bukkit.craftbukkit.block.data.CraftBlockData.createNewData(CraftBlockData.java:532) ~[Cardboard-1.19.2.jar:?]

at org.bukkit.craftbukkit.block.data.CraftBlockData.lambda$newData$0(CraftBlockData.java:512) ~[Cardboard-1.19.2.jar:?]

at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]

at org.bukkit.craftbukkit.block.data.CraftBlockData.newData(CraftBlockData.java:512) ~[Cardboard-1.19.2.jar:?]

at org.bukkit.craftbukkit.CraftServer.createBlockData(CraftServer.java:630) ~[Cardboard-1.19.2.jar:?]

at org.bukkit.craftbukkit.CraftServer.createBlockData(CraftServer.java:612) ~[Cardboard-1.19.2.jar:?]

at org.bukkit.Bukkit.createBlockData(Bukkit.java:2060) ~[paper-api-1.18.2-167.jar:?]

at org.bukkit.Material.createBlockData(Material.java:4096) ~[paper-api-1.18.2-167.jar:?]

at com.sk89q.worldedit.bukkit.WorldEditPlugin.lambda$initializeRegistries$0(WorldEditPlugin.java:227) ~[?:?]

at com.sk89q.worldedit.world.block.BlockType.computeDefaultState(BlockType.java:85) ~[?:?]

at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[?:?]

at com.sk89q.worldedit.world.block.BlockType.getDefaultState(BlockType.java:162) ~[?:?]

at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:354) ~[?:?]

at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:93) ~[?:?]

at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:63) ~[?:?]

at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]

at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:43) ~[?:?]

at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:30) ~[?:?]

at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]

at com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:126) ~[?:?]

at org.enginehub.piston.impl.CommandParser.lambda$isAcceptedByTypeParsers$7(CommandParser.java:497) ~[?:?]

at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]

at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]

at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]

at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]

at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]

at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]

at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]

at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]

at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]

at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]

at org.enginehub.piston.impl.CommandParser.isAcceptedByTypeParsers(CommandParser.java:492) ~[?:?]

at org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:429) ~[?:?]

at org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340) ~[?:?]

at org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240) ~[?:?]

at org.enginehub.piston.CommandManager.execute(CommandManager.java:154) ~[?:?]

at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]

at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]

at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]

at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]

at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]

at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]

at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-167.jar:?]

at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:924) ~[Cardboard-1.19.2.jar:?]

at org.cardboardpowered.impl.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:61) ~[Cardboard-1.19.2.jar:?]

at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]

at net.minecraft.class_2170.redirect$zdl000$performCommand(class_2170.java:545) ~[server-intermediary.jar:?]

at net.minecraft.class_2170.method_9249(class_2170.java:271) ~[server-intermediary.jar:?]

at net.minecraft.class_3244.method_45010(class_3244.java:3268) ~[server-intermediary.jar:?]

at net.minecraft.class_3244.method_44356(class_3244.java:1320) ~[server-intermediary.jar:?]

at net.minecraft.class_1255.method_5386(class_1255.java:68) ~[server-intermediary.jar:?]

at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]

at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]

at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]

at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]

at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]

at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]

at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]

at java.lang.Thread.run(Thread.java:833) [?:?]

Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Invalid ID at position 0: <--[HERE]

Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Invalid ID at position 0: <--[HERE]

**Comment by Domaman202** [comment]
Bro are you using a plugin or a mod? If it's a plugin - put a better mod)

**Comment by jonathanjdr** [comment]
Upload the full log & a mod list so we can get better context.

**Comment by samuelh2005** [comment]
You're using the plugin version of WorldEdit. Use the Fabric version of WorldEdit and put in the mods folder.
