### ISSUE TITLE
File Access Denied Error

### ISSUE THREAD

**Issue by DelsigMatt** [BukkitFabric/bukkit4fabric#415]
File Access Denied error throwing whenever I start the server and whilst certain events are fired. Seems to have little to no effect on overall function of the plugin.

[21:27:27] [Server thread/INFO]: [STDERR]: java.nio.file.AccessDeniedException: C:\Users\isaia
[21:27:27] [Server thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:521)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:240)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:115)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:110)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.forName0(Native Method)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.forName(Class.java:467)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:119)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:414)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3176.handler$zdn000$cardboard$init(class_3176.java:1223)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3176.method_3823(class_3176.java:150)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[21:27:27] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jonathanjdr** [comment]
https://github.com/CardboardPowered/cardboard/issues/408#issuecomment-1616128347 < Fixed there. You can run server jar as admin or allow full access to the Users\isaia directory.
