### ISSUE TITLE
Server crash when trying to place painting on the wall: java.lang.NoSuchMethodError: org/bukkit/event/hanging/HangingPlaceEvent.<init>

### ISSUE THREAD

**Issue by vadim-a-yegorov** [BukkitFabric/bukkit4fabric#419]
Fabric 1.18.2, Cardboard

Server crash when trying to place painting on the wall:

```
		java.lang.NoSuchMethodError: org/bukkit/event/hanging/HangingPlaceEvent.<init>(Lorg/bukkit/entity/Hanging;Lorg/bukkit/entity/Player;Lorg/bukkit/block/Block;Lorg/bukkit/block/BlockFace;Lorg/bukkit/inventory/ItemStack;)V (loaded from file:/home/ubuntu/.lodestone/instances/Technomania-85c3f95e/lib/paper-api-1.17-dev.jar by net.fabricmc.loader.impl.launch.knot.KnotClassLoader@ad430ac0) called from class net.minecraft.item.DecorationItem (loaded from file:/home/ubuntu/.lodestone/instances/Technomania-85c3f95e/.fabric/remappedJars/minecraft-1.18.2-0.14.21/server-intermediary.jar by net.fabricmc.loader.impl.launch.knot.KnotClassLoader@ad430ac0).
			at net.minecraft.item.DecorationItem.handler$zjf000$cardboard$bukkitUseOnBlock(DecorationItem.java:541) ~[server-intermediary.jar:?]
			at net.minecraft.item.DecorationItem.useOnBlock(DecorationItem.java:57) ~[server-intermediary.jar:?]
			at net.minecraft.item.ItemStack.useOnBlock(ItemStack.java:1221) ~[server-intermediary.jar:?]
			at net.minecraft.server.network.ServerPlayerInteractionManager.handler$zfa000$cardboard$interactBlock(ServerPlayerInteractionManager.java:846) ~[server-intermediary.jar:?]
			at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager.java) ~[server-intermediary.jar:?]
			at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler.java:1081) ~[server-intermediary.jar:?]
			at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket.java:30) ~[server-intermediary.jar:?]
			at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket.java:8) ~[server-intermediary.jar:?]
			at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:22) ~[server-intermediary.jar:?]
			at net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[server-intermediary.jar:?]
			at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:157) ~[server-intermediary.jar:?]
			at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[server-intermediary.jar:?]
			at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:808) ~[server-intermediary.jar:?]
			at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:165) ~[server-intermediary.jar:?]
			at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:131) ~[server-intermediary.jar:?]
			at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:790) ~[server-intermediary.jar:?]
			at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:784) ~[server-intermediary.jar:?]
			at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:116) ~[server-intermediary.jar:?]
			at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:768) ~[server-intermediary.jar:?]
			at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:701) ~[server-intermediary.jar:?]
			at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
			at java.lang.Thread.run(Thread.java:857) [?:?]

```

**Comment by wdog5** [comment]
missing events,it need to update bukkit api

**Comment by vadim-a-yegorov** [comment]
> missing events,it need to update bukkit api

Fixed by reverting to Cardboard # 59
