### ISSUE TITLE
Permission manager issue, possibly caused by misaligned events

### ISSUE THREAD

**Issue by tomkeuper** [BukkitFabric/bukkit4fabric#422]
I installed LuckPerms to manage plugin permissions but when joining I get the following message in the console. The player itself instantly gets kicked with the following message "Permissions data for your user was not loaded during the pre-login stage - unable to continue. Please try again later. If you are a server admin, please check the console for any errors."

The only plugins installed are Luckperms, SSX-connector (for server selector), TAB (doesnt enable), Vault 

LP is not installed as a fabric mod. And cardboard runs under a velocity proxy

> [19:06:16] [Server thread/WARN]: User {uuid} - MrCeasar doesn't have data pre-loaded, they have never been processed during pre-login in this session. - denying login.
[19:06:16] [Server thread/WARN]: Player MrCeasar has a non-LuckPerms permissible (org.bukkit.permissions.PermissibleBase)!
This is probably because you have multiple permission plugins installed.
Please make sure that LuckPerms is the only permission plugin installed on your server!
(unless you're performing a migration, in which case, just remember to remove your old permission plugin once you're done!)
[19:06:16] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@27b884f4[id={uuid} ,name=MrCeasar,properties={textures=[com.mojang.authlib.properties.Property@9e178dc]},legacy=false] (/192.168.2.1:59706): §7[§b§lL§3§lP§7]§r §cPermissions data for your user was not loaded during the pre-login stage - unable to continue. Please try again later. If you are a server admin, please check the console for any errors.
[19:06:16] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3222.method_7334()" because "$$1" is null
        at net.minecraft.class_3324.method_14570(class_3324.java:144) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_33800(class_3248.java:151) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:138) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.redirect$bhf000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:1063) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_18784(class_3248.java:73) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[19:06:16] [Server thread/INFO]: com.mojang.authlib.GameProfile@27b884f4[id={uuid} ,name=MrCeasar,properties={textures=[com.mojang.authlib.properties.Property@9e178dc]},legacy=false] (/192.168.2.1:59706) lost connection: §7[§b§lL§3§lP§7]§r §cPermissions data for your user was not loaded during the pre-login stage - unable to continue. Please try again later. If you are a server admin, please check the console for any errors.
[19:06:16] [Server thread/WARN]: handleDisconnection() called twice
[19:06:18] [Server thread/INFO]: [STDOUT]: isOnline: com.mojang.authlib.GameProfile@2f0875de[id={uuid} ,name=<null>,properties={},legacy=false], false

**Comment by pepomann** [comment]
i have the same error haha
somebody knows how to solve?
