### ISSUE TITLE
Failed to validate profile key: Invalid signature for profile public key.

### ISSUE THREAD

**Issue by DragonwolfAside** [BukkitFabric/bukkit4fabric#426]
Server: Fabric 1.19.2
Client: HMCL 3.5.5

I connected the offline server by a offline client, then the problem occur.
I tried to disable the `Cardboard-1.19.2.jar` then everything works well.
editing `enforce-secure-profile=false` dosen't work

fabric mods

- `fabric-api-0.76.0+1.19.2.jar`
- `Cardboard-1.19.2.jar`
- `iCommon-Fabric-1.19.2.jar`

Here is the server log when the problem occur

```text
[01:00:47] [User Authenticator #0/INFO]: UUID of player Aside is 6f4b4595-dca1-385d-9024-ebaf56aa08bc
[01:00:47] [Server thread/ERROR]: Failed to verify Services signature
java.security.SignatureException: Signature length not correct: got 1 but was expecting 512
        at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:213) ~[?:?]
        at java.security.Signature$Delegate.engineVerify(Signature.java:1415) ~[?:?]
        at java.security.Signature.verify(Signature.java:789) ~[?:?]
        at net.minecraft.class_7500.method_44171(class_7500.java:24) ~[server-intermediary.jar:?]
        at net.minecraft.class_7500.method_44173(class_7500.java:44) ~[server-intermediary.jar:?]
        at net.minecraft.class_7500.method_44177(class_7500.java:19) ~[server-intermediary.jar:?]
        at net.minecraft.class_7428$class_7443.method_44205(class_7428.java:79) ~[server-intermediary.jar:?]
        at net.minecraft.class_7428.method_43550(class_7428.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_43510(class_3248.java:725) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:112) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.redirect$zki000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:1063) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_18784(class_3248.java:73) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[01:00:47] [Server thread/ERROR]: Failed to validate profile key: Invalid signature for profile public key.
Try restarting your game.
[01:00:47] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@6de43e51[id=6f4b4595-dca1-385d-9024-ebaf56aa08bc,name=Aside,properties={},legacy=false] (/127.0.0.1:27286): Invalid signature for profile public key.
Try restarting your game.
[01:00:47] [Server thread/INFO]: com.mojang.authlib.GameProfile@6de43e51[id=6f4b4595-dca1-385d-9024-ebaf56aa08bc,name=Aside,properties={},legacy=false] (/127.0.0.1:27286) lost connection: Invalid signature for profile public key.
Try restarting your game.
[01:00:47] [Server thread/WARN]: handleDisconnection() called twice
```

Server log: [server_log.zip](https://github.com/CardboardPowered/cardboard/files/12064643/server_log.zip)

here's hmcl launcher website if you wanna reproduce

HMCL website: [https://hmcl.huangyuhui.net/download/](https://hmcl.huangyuhui.net/download/)
Server properties: [server.properties.zip](https://github.com/CardboardPowered/cardboard/files/12064638/server.properties.zip)

Plz fix qwq

**Comment by HowardZHY** [comment]
https://github.com/CardboardPowered/cardboard/blob/ver/1.19.2/src/main/java/org/cardboardpowered/mixin/network/MixinServerLoginNetworkHandler.java
It should be something with this i guess

**Comment by kaindand** [comment]
I have the same problem
