### ISSUE TITLE
1.18.2 Fail launch.

### ISSUE THREAD

**Issue by PutEgg** [BukkitFabric/bukkit4fabric#436]
PS D:\localBuildServer> java -Xmx8G -jar fabric-server-mc.1.18.2-loader.0.14.22-launcher.0.11.2.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[13:38:32] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.22
[13:38:32] [ForkJoinPool-1-worker-10/WARN]: Mod lottweaks uses the version 2.3.2a which isn't compatible with Loader's extended semantic version format (Could not parse version number component '2a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[13:38:32] [ForkJoinPool-1-worker-4/WARN]: Mod com_github_isaiahpatton_specialsource uses the version master-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'master'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[13:38:32] [main/INFO]: Loading 48 mods:
        - architectury 4.11.93
        - badpackets 0.1.3
        - cardboard 64
           \-- com_github_isaiahpatton_specialsource master-SNAPSHOT
        - cloth-config 6.5.102
           \-- cloth-basic-math 0.6.1
        - effortless 1.6.2
        - fabric-api 0.76.0+1.18.2
           |-- fabric-api-base 0.4.5+64b7c69360
           |-- fabric-api-lookup-api-v1 1.6.3+2373a54560
           |-- fabric-biome-api-v1 8.0.7+e83becad60
           |-- fabric-block-api-v1 1.0.0+ee3621fc60
           |-- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560
           |-- fabric-command-api-v1 1.1.10+d7c144a860
           |-- fabric-commands-v0 0.2.9+b4f4f6cd60
           |-- fabric-containers-v0 0.1.24+d7c144a860
           |-- fabric-content-registries-v0 3.1.3+c85f2e3860
           |-- fabric-convention-tags-v1 1.1.0+43ce63a460
           |-- fabric-crash-report-info-v1 0.2.1+ee261a3e60
           |-- fabric-data-generation-api-v1 3.1.0+6c70b68e60
           |-- fabric-dimensions-v1 2.1.21+489d6f8260
           |-- fabric-entity-events-v1 1.4.9+d7c144a860
           |-- fabric-events-interaction-v0 0.4.20+d7c144a860
           |-- fabric-events-lifecycle-v0 0.2.22+d7c144a860
           |-- fabric-game-rule-api-v1 1.0.13+d7c144a860
           |-- fabric-item-api-v1 1.6.2+8165403660
           |-- fabric-item-groups-v0 0.3.16+91896a4960
           |-- fabric-key-binding-api-v1 1.0.12+54e5b2ec60
           |-- fabric-keybindings-v0 0.2.10+b4f4f6cd60
           |-- fabric-lifecycle-events-v1 2.1.1+cc71601c60
           |-- fabric-loot-api-v2 1.1.2+1997ad1260
           |-- fabric-loot-tables-v1 1.1.4+e747827960
           |-- fabric-mining-level-api-v1 2.1.6+cc71601c60
           |-- fabric-models-v0 0.3.7+d7c144a860
           |-- fabric-networking-api-v1 1.0.24+2d30af4b60
           |-- fabric-networking-v0 0.3.11+b4f4f6cd60
           |-- fabric-object-builder-api-v1 2.1.5+032c981d60
           |-- fabric-particles-v1 0.2.13+526dc1ac60
           |-- fabric-registry-sync-v0 0.9.12+bb2e047760
           |-- fabric-renderer-api-v1 0.5.0+bf48649860
           |-- fabric-renderer-indigo 0.6.1+03e2b68760
           |-- fabric-renderer-registries-v1 3.2.12+b4f4f6cd60
           |-- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60
           |-- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60
           |-- fabric-rendering-v0 1.1.14+b4f4f6cd60
           |-- fabric-rendering-v1 1.10.8+54e5b2ec60
           |-- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660
           |-- fabric-resource-loader-v0 0.5.3+047a5ecb60
           |-- fabric-screen-api-v1 1.0.11+d882b91560
           |-- fabric-screen-handler-api-v1 1.2.3+1f6558e860
           |-- fabric-textures-v0 1.0.13+3ac43d9560
           |-- fabric-transfer-api-v1 1.6.4+f4563ac860
           \-- fabric-transitive-access-wideners-v1 1.1.0+e747827960
        - fabricloader 0.14.22
        - icommon 1.18
        - java 17
        - lottweaks 2.3.2a
           \-- reach-entity-attributes 2.1.1
        - minecraft 1.18.2
[13:38:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/localBuildServer/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[13:38:32] [main/INFO]: Compatibility level set to JAVA_16
[13:38:32] [main/INFO]: Compatibility level set to JAVA_17
[13:38:32] [main/INFO]: Please wait, Scanning plugins for events...
[13:38:32] [main/INFO]: Found: 0 (Took: 0ms)
[13:38:32] [main/INFO]: Loading Libraries...
[13:38:32] [main/INFO]: Debug: Loading library paper-api-1.17-dev.jar
[13:38:32] [main/INFO]: Debug: Loading library sqlite-jdbc-3.21.0.1.jar
[13:38:32] [main/INFO]: Debug: Loading library mysql-connector-java-5.1.46.jar
[13:38:32] [main/INFO]: Debug: Loading library commons-lang-2.6.jar
[13:38:32] [main/INFO]: Debug: Loading library commons-collections4-4.4.jar
[13:38:32] [main/INFO]: Debug: Loading library commons-collections-3.2.1.jar
[13:38:32] [main/INFO]: Downloading org.cardboardpowered:intermediary-adapter:7.3...
[13:38:33] [main/WARN]: Failed to download: org.cardboardpowered:intermediary-adapter:7.3
java.io.FileNotFoundException: https://github.com/CardboardPowered/worldedit-adapters/releases/download/1.17.1/we-adapter-for-cardboard.jar
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at org.cardboardpowered.library.LibraryManager.download(LibraryManager.java:116) [Cardboard-1.18.2.jar:?]
        at org.cardboardpowered.library.LibraryManager.run(LibraryManager.java:84) [Cardboard-1.18.2.jar:?]
        at org.cardboardpowered.mixin.CardboardMixinPlugin.loadLibs(CardboardMixinPlugin.java:78) [Cardboard-1.18.2.jar:?]
        at org.cardboardpowered.mixin.CardboardMixinPlugin.onLoad(CardboardMixinPlugin.java:54) [Cardboard-1.18.2.jar:?]
        at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) [fabric-loader-0.14.22.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.18.2-loader.0.14.22-launcher.0.11.2.jar:0.11.2]
[13:38:33] [main/WARN]: Attempting download of 'intermediary-adapter-7.3.jar' again (2/2)
[13:38:33] [main/INFO]: Downloading org.cardboardpowered:intermediary-adapter:7.3...
[13:38:34] [main/WARN]: Failed to download: org.cardboardpowered:intermediary-adapter:7.3
java.io.FileNotFoundException: https://github.com/CardboardPowered/worldedit-adapters/releases/download/1.17.1/we-adapter-for-cardboard.jar
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at org.cardboardpowered.library.LibraryManager.download(LibraryManager.java:116) [Cardboard-1.18.2.jar:?]
        at org.cardboardpowered.library.LibraryManager.run(LibraryManager.java:84) [Cardboard-1.18.2.jar:?]
        at org.cardboardpowered.mixin.CardboardMixinPlugin.loadLibs(CardboardMixinPlugin.java:78) [Cardboard-1.18.2.jar:?]
        at org.cardboardpowered.mixin.CardboardMixinPlugin.onLoad(CardboardMixinPlugin.java:54) [Cardboard-1.18.2.jar:?]
        at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) [fabric-loader-0.14.22.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.18.2-loader.0.14.22-launcher.0.11.2.jar:0.11.2]
[13:38:34] [main/WARN]: Restart the server to attempt downloading 'intermediary-adapter-7.3.jar' again.
[13:38:34] [main/INFO]: Architectury Mod detected! Disabling async chat from NetworkHandler.
[13:38:34] [main/INFO]: Architectury Mod detected! Using alternative async chat from PlayerManager
[13:38:34] [main/INFO]: =======================================================
[13:38:34] [main/INFO]:  iCommon - Isaiah's common library for mods.
[13:38:34] [main/INFO]:  Copyright (c) 2018-2023 Isaiah. Running on MC 1.18.2
[13:38:34] [main/INFO]: =======================================================
[13:38:34] [main/INFO]: Applying mixin: MixinMinecraftServer...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinMinecraftServer...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinEntity...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinPlayer...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinBlockEntity...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinChestBlockEntity...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinCampfireBlockEntity...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinScreenHandler...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinChunkGenerator...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinPersistentStateManager...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinPlayerManager...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinHeighttmap...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinLeavesBlock...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinCat...
[13:38:34] [main/INFO]: Applying mixin: R1_18.MixinWorld_18...
[13:38:40] [main/INFO]:
[13:38:40] [main/INFO]: Cardboard - CardboardPowered.org
[13:38:40] [main/INFO]:
[13:38:40] [main/INFO]: Registered '6' iCommon events.
[13:38:41] [main/INFO]: Reflection working: false
[13:38:41] [main/INFO]: Cardboard mod Loaded.
[13:38:41] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'icommon'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.22.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.18.2-loader.0.14.22-launcher.0.11.2.jar:0.11.2]
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'icommon'
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
        ... 8 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: me.isaiah.common.R117.ICommonMod_117
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: me.isaiah.common.R117.ICommonMod_117
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
        ... 8 more

**Comment by fr1g** [comment]
bro this even cannot startup with no extra mods! lmao
