### ISSUE TITLE
Mod incompatibility with Immersive Portals

### ISSUE THREAD

**Issue by Olivecba** [BukkitFabric/bukkit4fabric#437]
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Replace mod 'Immersive Portals' (immersive_portals) 3.2.5 with any version that is compatible with:
                 - cardboard 14
Unmet dependency listing:
         - Mod 'Immersive Portals' (immersive_portals) 3.2.5 is incompatible with any version of mod 'Cardboard' (cardboard), but a matching version is present: 14!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]

**Comment by Hedwig7s** [comment]
Considering the fact that Immersive Portals explicitly declares itself incompatible I think they already know

**Comment by Olivecba** [comment]
> Considering the fact that Immersive Portals explicitly declares itself incompatible I think they already know

Probably should've checked their modpage, my bad
