### ISSUE TITLE
Skript Crash

### ISSUE THREAD

**Issue by jorisdigitalREAL** [BukkitFabric/bukkit4fabric#438]
I really have to say this mod is what I've been looking for for a long time! There are few or no bugs and errors.

But I got this error from "Skript" when starting the server in 1.19.2:

```
[13:19:04] [Server thread/FATAL]: Error occurred while enabling script v2.6.4 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 1524 out of bounds for length 1227
         at ch.njol.Skript.aliases.AliasesMap.getEntry(AliasesMap.java:144) ~[?:?]
         at ch.njol.Skript.aliases.AliasesMap.exactMatch(AliasesMap.java:207) ~[?:?]
         at ch.njol.Skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:297) ~[?:?]
         at ch.njol.Skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:694) ~[?:?]
         at ch.njol.Skript.aliases.AliasesParser.loadAlias(AliasesParser.java:603) ~[?:?]
         at ch.njol.Skript.aliases.AliasesParser.load(AliasesParser.java:121) ~[?:?]
         at ch.njol.Skript.aliases.Aliases.load(Aliases.java:510) ~[?:?]
         at ch.njol.Skript.aliases.Aliases.load(Aliases.java:496) ~[?:?]
         at ch.njol.Skript.aliases.Aliases.lambda$loadDirectory$1(Aliases.java:479) ~[?:?]
         at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
         at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
         at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
         at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
         at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
         at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
         at ch.njol.Skript.aliases.Aliases.loadDirectory(Aliases.java:472) ~[?:?]
         at ch.njol.Skript.aliases.Aliases.loadInternal(Aliases.java:437) ~[?:?]
         at ch.njol.Skript.aliases.Aliases.load(Aliases.java:393) ~[?:?]
         at ch.njol.Skript.Skript.onEnable(Skript.java:472) ~[?:?]
         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:257) ~[Cardboard-1.19.2.jar:?]
         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[Cardboard-1.19.2.jar:?]
         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-167.jar:?]
         at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:503) ~[Cardboard-1.19.2.jar:?]
         at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:433) ~[Cardboard-1.19.2.jar:?]
         at net.minecraft.server.MinecraftServer.handler$zzd000$cardboard$afterWorldLoad(MinecraftServer.java:2949) ~[server-intermediary.jar:?]
         at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:330) ~[server-intermediary.jar:?]
         at net.minecraft.class_3176.method_3823(class_3176.java:172) ~[server-intermediary.jar:?]
         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636) ~[server-intermediary.jar:?]
         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
         at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Nicolol1234** [comment]
Skript = bad

**Comment by TinyMandalorian** [comment]
> Skript = bad

wow you were so helpful -_-

**Comment by Nicolol1234** [comment]
What i'm trying to say is that everything on skript has his standard plugin form

**Comment by TinyMandalorian** [comment]
💀 no what

**Comment by EysseW** [comment]
So what, you can't use Skript with cardboard? Using Skript is the major reason I want to use cardboard.
