### ISSUE TITLE
[1.20.4] Unable to open world, game crashes, server does on multiplayer as well.

### ISSUE THREAD

**Issue by timmbobb** [BukkitFabric/bukkit4fabric#467]
[03:09:56] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.10
[03:09:56] [ForkJoinPool-1-worker-3/WARN]: Mod icommon-bundle uses the version bundle which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'bundle'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[03:09:56] [main/INFO]: Loading 101 mods:
	- armorposer 4.2.0
	- audioplayer 1.20.4-1.9.1
	   \-- admiral 0.4.4+1.20.4
	- betterdeserttemples 1.20.4-Fabric-3.4.1
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.20.4-Fabric-4.4.2
	   \-- org_reflections_reflections 0.10.2
	- betterendisland 1.20.4-Fabric-2.4.1
	   \-- org_reflections_reflections 0.10.2
	- betterfortresses 1.20.4-Fabric-2.4.2
	   \-- org_reflections_reflections 0.10.2
	- betterjungletemples 1.20.4-Fabric-2.4.1
	   \-- org_reflections_reflections 0.10.2
	- bettermineshafts 1.20.4-Fabric-4.4.1
	   \-- org_reflections_reflections 0.10.2
	- betteroceanmonuments 1.20.4-Fabric-3.4.1
	   \-- org_reflections_reflections 0.10.2
	- betterstrongholds 1.20.4-Fabric-4.4.1
	   \-- org_reflections_reflections 0.10.2
	- betterwitchhuts 1.20.4-Fabric-3.4.1
	   \-- org_reflections_reflections 0.10.2
	- cardboard 1
	   \-- net_md-5_specialsource 1.11.2
	- carpet 1.4.128+v231205
	- carpet-fixes 1.20-1.17.0
	   \-- mixinextras 0.3.5
	- carpet-tis-addition 1.57.1
	   |-- conditional-mixin 0.5.1
	   \-- mixinextras 0.3.5
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- coordfinder 1.20.4-1.1.0
	   \-- admiral 0.4.4+1.20.4
	- elytra-trims 2.1.2
	   \-- mixinsquared 0.1.2-beta.4
	- fabric-api 0.97.0+1.20.4
	   |-- fabric-api-base 0.4.37+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.50+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.17+78d798af4f
	   |-- fabric-block-api-v1 1.0.17+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.5+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.47+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.8+78d798af4f
	   |-- fabric-command-api-v1 1.2.42+f71b366f4f
	   |-- fabric-command-api-v2 2.2.21+78d798af4f
	   |-- fabric-commands-v0 0.2.59+df3654b34f
	   |-- fabric-containers-v0 0.1.87+df3654b34f
	   |-- fabric-content-registries-v0 5.0.16+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.11+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.24+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.5+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.5+5c0133444f
	   |-- fabric-dimensions-v1 2.1.62+78d798af4f
	   |-- fabric-entity-events-v1 1.6.2+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.2+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.75+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.47+78d798af4f
	   |-- fabric-item-api-v1 2.3.0+bcdd12964f
	   |-- fabric-item-group-api-v1 4.0.27+ee30b13a4f
	   |-- fabric-key-binding-api-v1 1.0.42+78d798af4f
	   |-- fabric-keybindings-v0 0.2.40+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.10+78d798af4f
	   |-- fabric-message-api-v1 6.0.6+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.66+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.9+78d798af4f
	   |-- fabric-models-v0 0.4.8+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.8+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.1.0+dba1195c4f
	   |-- fabric-particles-v1 1.1.8+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.21+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.20+ee30b13a4f
	   |-- fabric-renderer-api-v1 3.2.5+78d798af4f
	   |-- fabric-renderer-indigo 1.5.5+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.54+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.2+e761c6694f
	   |-- fabric-rendering-v0 1.1.57+df3654b34f
	   |-- fabric-rendering-v1 3.2.1+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.15+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.21+ee30b13a4f
	   |-- fabric-screen-api-v1 2.0.18+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.56+78d798af4f
	   |-- fabric-sound-api-v1 1.0.18+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.12+90f2d7b14f
	   \-- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricexporter 1.0.11
	- fabricloader 0.15.10
	   \-- mixinextras 0.3.5
	- icommon-bundle bundle
	   \-- icommon 1.20.2
	- invview 1.4.14-1.20.4+
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- sgui 1.3.0+1.20.2
	- java 17
	- jei 17.3.0.49
	- lithium 0.12.1
	- minecraft 1.20.4
	- moonlight 1.20.4-2.10.3
	- mr_no_trialchambers 1.2
	- nochatreports 1.20.4-v2.6.0
	- shulkerboxtooltip 4.0.8+1.20.4
	- spark 1.10.58
	   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- viafabric 0.4.13+65-main
	   |-- cotton-client-commands 1.1.0+1.15.2
	   |-- org_yaml_snakeyaml 2.2
	   |-- viafabric-mc120 0.4.13+65-main
	   \-- viaversion 4.9.4-SNAPSHOT
	- viewdistancefix 1.20.4-1.0.2
	- voicechat 1.20.4-2.5.12
	   \-- fabric-key-binding-api-v1 1.0.39+f4b7e42432
	- xaerominimap 24.1.1
	- xaeroworldmap 1.38.4
	- yungsapi 1.20.4-Fabric-4.4.2
	   |-- org_javassist_javassist 3.29.2-GA
	   \-- org_reflections_reflections 0.10.2
[03:09:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[03:09:57] [main/INFO]: Compatibility level set to JAVA_17
[03:09:57] [main/INFO]: Loading Libraries...
[03:09:57] [main/INFO]: Debug: Loading library paper-api-1.19.4-550.jar
[03:09:57] [main/INFO]: Debug: Loading library sqlite-jdbc-3.41.0.0.jar
[03:09:57] [main/INFO]: Debug: Loading library mysql-connector-j-8.0.32.jar
[03:09:57] [main/INFO]: Debug: Loading library commons-lang-2.6.jar
[03:09:57] [main/INFO]: Debug: Loading library commons-collections4-4.4.jar
[03:09:57] [main/INFO]: Debug: Loading library commons-collections-3.2.1.jar
[03:09:57] [main/INFO]: Loaded configuration file for Lithium: 129 options available, 0 override(s) found
[03:09:58] [main/INFO]: =======================================================
[03:09:58] [main/INFO]:  iCommon - Isaiah's common library for mods.
[03:09:58] [main/INFO]:  Copyright (c) 2018-2023 Isaiah. Running on MC 1.20.4
[03:09:58] [main/INFO]: =======================================================
[03:09:58] [main/INFO]: Applying mixin: MixinMinecraftServer...
[03:09:59] [main/INFO]: Applying mixin: R1_20.MixinMinecraftServer...
[03:09:59] [main/INFO]: Applying mixin: R1_20.MixinEntity...
[03:09:59] [main/INFO]: Applying mixin: R1_20.MixinPlayer...
[03:09:59] [main/INFO]: Applying mixin: R1_20.MixinBlockEntity...
[03:09:59] [main/INFO]: Applying mixin: R1_20.MixinChestBlockEntity...
[03:09:59] [main/INFO]: Lithium detected
[03:09:59] [main/INFO]: Lithium detected
[03:09:59] [main/INFO]: Lithium detected
[03:09:59] [main/INFO]: Lithium detected
[03:09:59] [main/INFO]: Lithium detected
[03:09:59] [main/INFO]: Applying mixin: R1_20.MixinScreenHandler...
[03:09:59] [main/INFO]: Applying mixin: R1_20.MixinChunkGenerator...
[03:09:59] [main/INFO]: Applying mixin: R1_20.MixinPersistentStateManager...
[03:09:59] [main/INFO]: Applying mixin: R1_20.MixinPlayerManager...
[03:09:59] [main/INFO]: Applying mixin: R1_20.MixinHeighttmap...
[03:09:59] [main/INFO]: Applying mixin: R1_20.MixinLeavesBlock...
[03:09:59] [main/INFO]: Applying mixin: R1_20.MixinCat...
[03:09:59] [main/INFO]: Applying mixin: R1_20.MixinWorld_18...
[03:09:59] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[03:09:59] [main/WARN]: Failed to get system info for Microarchitecture
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.cpuVendor" is null
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:?]
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[server-intermediary.jar:?]
	at net.minecraft.class_6396.method_37130(class_6396.java:128) ~[server-intermediary.jar:?]
	at net.minecraft.class_6396.method_37146(class_6396.java:75) ~[server-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[server-intermediary.jar:?]
	at net.minecraft.class_6396.method_37128(class_6396.java:75) ~[server-intermediary.jar:?]
	at net.minecraft.class_6396.method_37143(class_6396.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[server-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:36) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:277) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:99) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.4.jar:1.0.1]
[03:10:01] [main/WARN]: Method overwrite conflict for method_5800 in carpet-fixes.mixins.json:itemFixes.ItemEntity_lightningKillsDropsMixin from mod carpet-fixes, previously written by carpet.mixins.ItemEntityMixin. Skipping method.
[03:10:04] [main/WARN]: @Final field field_9194:Ljava/util/Map; in bukkitfabric.mixins.json:MixinExplosion from mod cardboard should be final
[03:10:05] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.4.jar:1.0.1]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:106) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1808 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:65) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1118) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1114) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:405) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1391) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:929) ~[server-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1253) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:106) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:65) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1118) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1114) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:405) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1391) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:929) ~[server-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1253) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:106) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method lifetimeTracker_recordSpawning_item_minecart(Lnet/minecraft/class_1297;)Lnet/minecraft/class_1297; in carpet-tis-addition.mixins.json:command.lifetime.spawning.item.MinecartItemMixin from mod carpet-tis-addition failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap carpet-tis-addition-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:65) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1118) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1114) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:405) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1391) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:929) ~[server-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1253) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:106) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	... 4 more

**Comment by axlecoffee** [comment]
@timmbobb please upload your log or join the discord.
