### ISSUE TITLE
Issue on 1.20.4

### ISSUE THREAD

**Issue by SaGye9816** [BukkitFabric/bukkit4fabric#476]
`[23:06:33] [Server thread/INFO]: [STDOUT]: net/minecraft/class_2535
[23:06:33] [Server thread/FATAL]: Could not load 'plugins\worldedit-bukkit-7.3.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/sk89q/worldedit/bukkit/WorldEditPlugin has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:148) ~[Cardboard-1.20.4%20(1).jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:411) ~[paper-api-1.19.4-550.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:319) ~[paper-api-1.19.4-550.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:115) ~[paper-api-1.19.4-550.jar:?]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:483) ~[Cardboard-1.20.4%20(1).jar:?]
        at net.minecraft.class_3176.handler$zzb000$cardboard$init(class_3176.java:717) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:147) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsupportedClassVersionError: com/sk89q/worldedit/bukkit/WorldEditPlugin has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:256) ~[Cardboard-1.20.4%20(1).jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:200) ~[Cardboard-1.20.4%20(1).jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:133) ~[Cardboard-1.20.4%20(1).jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[Cardboard-1.20.4%20(1).jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[Cardboard-1.20.4%20(1).jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144) ~[Cardboard-1.20.4%20(1).jar:?]
        ... 9 more
[23:06:33] [Server thread/FATAL]: Could not load 'plugins\worldguard-bukkit-7.0.9-dist (1).jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [WorldEdit]. Please download and install these plugins to run 'WorldGuard'.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:287) ~[paper-api-1.19.4-550.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:115) ~[paper-api-1.19.4-550.jar:?]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:483) ~[Cardboard-1.20.4%20(1).jar:?]
        at net.minecraft.class_3176.handler$zzb000$cardboard$init(class_3176.java:717) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:147) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by r1sk01** [comment]
This is to do with the version of Java you're using on your machine, not Cardboard.
