### ISSUE TITLE
Mixin Issue

### ISSUE THREAD

**Issue by RosenheimL** [BukkitFabric/bukkit4fabric#478]
[Apoli](https://github.com/apace100/apoli) is conflicting with [Cardboard](https://github.com/CardboardPowered/).

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3324::preventEndExitSpawnPointSetting with priority 800 cannot inject into net/minecraft/class_3324::method_14556(Lnet/minecraft/class_3222;Z)Lnet/minecraft/class_3222; merged by org.cardboardpowered.mixin.MixinPlayerManager with priority 1000 [PREINJECT Applicator Phase -> apoli.mixins.json:LoginMixin from mod apoli -> Prepare Injections ->  -> redirect$zem000$apoli$preventEndExitSpawnPointSetting(Lnet/minecraft/class_3222;Lnet/minecraft/class_5321;Lnet/minecraft/class_2338;FZZLnet/minecraft/class_3222;Z)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:306)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:241)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3427)
	at java.base/java.lang.Class.getMethods(Class.java:2019)
	at com.supermartijn642.core.registry.RegistryEntryAcceptor$Handler.gatherAnnotatedFields(RegistryEntryAcceptor.java:114)
	at com.supermartijn642.core.CoreLib.beforeInitialize(CoreLib.java:75)
	at net.minecraft.class_310.handler$hoc000$supermartijn642corelib$beforeInit(class_310.java:32010)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

```

## Mod list
```
- additionalentityattributes 1.3.0+1.20.0 via apoli
- advanced_runtime_resource_pack 0.6.7 via enhancedblockentities
- ae2 15.2.8
- ae2-emi-crafting 1.3.1
- ae2wtlib 15.2.1-fabric
- almanac 0.5.0
- amecs 1.3.10+mc.1.20.1
- amecsapi 1.4.0+mc1.20-pre1 via amecs
- anvil_fix 20.0.1
- apoli 2.9.0 via origins
- appleskin 2.5.1+mc1.20
- apugli 2.6.5+1.20.1-fabric via touhouorigins
- aquatictorches 1.0.1
- arcadiandream 0.1.0
- architectury 9.2.14
- athena 3.1.2
- badpackets 0.4.3
- balm-fabric 7.3.6
- betteranimationscollection 8.0.0
- betterarcheology 1.1.9-1.20.1
- betterdeserttemples 1.20-Fabric-3.0.3
- betterendisland 1.20-Fabric-2.0.6
- betterf3 7.0.2
- betterfortresses 1.20-Fabric-2.0.6
- betterjungletemples 1.20-Fabric-2.0.5
- bettermineshafts 1.20-Fabric-4.0.4
- bettermounthud 1.2.2
- betteroceanmonuments 1.20-Fabric-3.0.4
- betterpingdisplay 1.1.1
- betterwitchhuts 1.20-Fabric-3.0.3
- blue_endless_jankson 1.2.2 via owo
- bobby 5.0.1
- c2me 0.2.0+alpha.11.5
- c2me-base 0.2.0+alpha.11.5 via c2me
- c2me-client-uncapvd 0.2.0+alpha.11.5 via c2me
- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.5 via c2me
- c2me-fixes-general-threading-issues 0.2.0+alpha.11.5 via c2me
- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.5 via c2me
- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.5 via c2me
- c2me-notickvd 0.2.0+alpha.11.5 via c2me
- c2me-opts-allocs 0.2.0+alpha.11.5 via c2me
- c2me-opts-chunk-access 0.2.0+alpha.11.5 via c2me
- c2me-opts-chunkio 0.2.0+alpha.11.5 via c2me
- c2me-opts-math 0.2.0+alpha.11.5 via c2me
- c2me-opts-scheduling 0.2.0+alpha.11.5 via c2me
- c2me-opts-worldgen-general 0.2.0+alpha.11.5 via c2me
- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.5 via c2me
- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.5 via c2me
- c2me-rewrites-chunkio 0.2.0+alpha.11.5 via c2me
- c2me-server-utils 0.2.0+alpha.11.5 via c2me
- c2me-threading-chunkio 0.2.0+alpha.11.5 via c2me
- c2me-threading-lighting 0.2.0+alpha.11.5 via c2me
- c2me-threading-worldgen 0.2.0+alpha.11.5 via c2me
- cactusconfig 2.1.1+knot+1.20.1 via crops_love_rain
- caffeineconfig 1.3.0+1.17 via sodium-extra
- calio 1.11.0 via apoli
- cameraoverhaul 1.4.1-fabric-universal
- cardboard 7
- cardinal-components-base 5.2.1 via comforts
- cardinal-components-block 5.2.1 via polymorph
- cardinal-components-entity 5.2.1 via comforts
- cardinal-components-item 5.2.1 via polymorph
- catjammies 1.0.0-1.20.1
- cc_tweaked_cobalt 0.9.3 via computercraft
- chat_heads 0.12.6
- chipped 3.0.6
- chunky 1.3.146
- chunkyborder 1.1.53
- chunkyextended 2.1.1
- cleardespawn 1.1.15
- cloth-basic-math 0.6.1 via cloth-config
- cloth-config 11.1.118
- clumps 12.0.0.4
- collective 7.70
- com_electronwill_night-config_core 3.6.7 via computercraft
- com_electronwill_night-config_toml 3.6.7 via computercraft
- com_eliotlash_mclib_mclib 20 via geckolib
- com_github_isaiahpatton_specialsource master-SNAPSHOT via cardboard
- com_ibm_async_asyncutil 0.1.0 via c2me
- com_jcraft_jzlib 1.1.3 via computercraft
- com_teamresourceful_bytecodecs 1.0.2 via resourcefullib
- com_teamresourceful_yabn 1.0.3 via resourcefullib
- com_twelvemonkeys_common_common-image 3.10.0 via yet_another_config_lib_v3
- com_twelvemonkeys_common_common-io 3.10.0 via yet_another_config_lib_v3
- com_twelvemonkeys_common_common-lang 3.10.0 via yet_another_config_lib_v3
- com_twelvemonkeys_imageio_imageio-core 3.10.0 via yet_another_config_lib_v3
- com_twelvemonkeys_imageio_imageio-metadata 3.10.0 via yet_another_config_lib_v3
- com_twelvemonkeys_imageio_imageio-webp 3.10.0 via yet_another_config_lib_v3
- com_typesafe_config 1.4.2 via bobby
- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT via krypton
- comforts 6.3.5+1.20.1
- commonnetworking 1.0.5-1.20.1
- completeconfig 2.5.2
- completeconfig-base 2.5.2 via completeconfig
- completeconfig-gui-cloth 2.5.2 via completeconfig
- completeconfig-gui-yacl 2.5.2 via completeconfig
- computercraft 1.111.0
- conditional-mixin 0.3.2 via moreculling
- config_toolkit 1.0.0 via extended_drawers
- cooperative 1.0.0
- coroutil 1.20.1-1.3.7
- creeperoverhaul 3.0.2
- crops_love_rain 1.4.0
- croptopia 3.0.3
- croptopia_additions 2.0.0
- crowdin-translate 1.4+1.19.3 via sodium-extra
- ctov 3.4.4
- cullleaves 3.2.0
- debugify 1.20.1+2.0
- doubledoors 5.7
- dramaticdoors 1.20.1-3.2.3
- dynamic_fps 3.6.0
- dynamictrim 1.4.1
- easymagic 8.0.1
- eccentrictome 1.10.2+1.0.2+1.20.1+fabric
- emi 1.1.10+1.20.1+fabric
- emi_enchanting 0.1.0+1.20.1
- emi_loot 0.6.6+1.20.1
- emienchants 1.0.0
- emiffect 1.1.2+mc1.20.1
- emitrades 1.2.1+mc1.20.1
- enhancedblockentities 0.9+1.20
- entity_model_features 2.1.3
- entity_texture_features 6.1.3
- entityculling 1.6.6
- epherolib 1.2.0
- explorerscompass 1.20.1-2.2.3-fabric
- extended_drawers 2.1.1+mc.1.20.1
- extra-mod-integrations 0.4.6+1.20.1
- fabric-api 0.92.2+1.20.1
- fabric-api-base 0.4.31+1802ada577 via fabric-api
- fabric-api-lookup-api-v1 1.6.36+1802ada577 via fabric-api
- fabric-biome-api-v1 13.0.13+1802ada577 via fabric-api
- fabric-block-api-v1 1.0.11+1802ada577 via fabric-api
- fabric-block-view-api-v2 1.0.1+1802ada577 via fabric-api
- fabric-blockrenderlayer-v1 1.1.41+1802ada577 via fabric-api
- fabric-client-tags-api-v1 1.1.2+1802ada577 via fabric-api
- fabric-command-api-v1 1.2.34+f71b366f77 via fabric-api
- fabric-command-api-v2 2.2.13+1802ada577 via fabric-api
- fabric-commands-v0 0.2.51+df3654b377 via fabric-api
- fabric-containers-v0 0.1.64+df3654b377 via fabric-api
- fabric-content-registries-v0 4.0.11+1802ada577 via fabric-api
- fabric-convention-tags-v1 1.5.5+1802ada577 via fabric-api
- fabric-crash-report-info-v1 0.2.19+1802ada577 via fabric-api
- fabric-data-attachment-api-v1 1.0.0+de0fd6d177 via fabric-api
- fabric-data-generation-api-v1 12.3.4+1802ada577 via fabric-api
- fabric-dimensions-v1 2.1.54+1802ada577 via fabric-api
- fabric-entity-events-v1 1.6.0+1c78457f77 via fabric-api
- fabric-events-interaction-v0 0.6.2+1802ada577 via fabric-api
- fabric-events-lifecycle-v0 0.2.63+df3654b377 via fabric-api
- fabric-game-rule-api-v1 1.0.40+1802ada577 via fabric-api
- fabric-item-api-v1 2.1.28+1802ada577 via fabric-api
- fabric-item-group-api-v1 4.0.12+1802ada577 via fabric-api
- fabric-key-binding-api-v1 1.0.37+1802ada577 via fabric-api
- fabric-keybindings-v0 0.2.35+df3654b377 via fabric-api
- fabric-language-kotlin 1.11.0+kotlin.2.0.0
- fabric-lifecycle-events-v1 2.2.22+1802ada577 via fabric-api
- fabric-loot-api-v2 1.2.1+1802ada577 via fabric-api
- fabric-loot-tables-v1 1.1.45+9e7660c677 via fabric-api
- fabric-message-api-v1 5.1.9+1802ada577 via fabric-api
- fabric-mining-level-api-v1 2.1.50+1802ada577 via fabric-api
- fabric-model-loading-api-v1 1.0.3+1802ada577 via fabric-api
- fabric-models-v0 0.4.2+9386d8a777 via fabric-api
- fabric-networking-api-v1 1.3.11+1802ada577 via fabric-api
- fabric-networking-v0 0.3.51+df3654b377 via fabric-api
- fabric-object-builder-api-v1 11.1.3+1802ada577 via fabric-api
- fabric-particles-v1 1.1.2+1802ada577 via fabric-api
- fabric-recipe-api-v1 1.0.21+1802ada577 via fabric-api
- fabric-registry-sync-v0 2.3.3+1802ada577 via fabric-api
- fabric-renderer-api-v1 3.2.1+1802ada577 via fabric-api
- fabric-renderer-indigo 1.5.2+85287f9f77 via fabric-api
- fabric-renderer-registries-v1 3.2.46+df3654b377 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777 via fabric-api
- fabric-rendering-fluids-v1 3.0.28+1802ada577 via fabric-api
- fabric-rendering-v0 1.1.49+df3654b377 via fabric-api
- fabric-rendering-v1 3.0.8+1802ada577 via fabric-api
- fabric-resource-conditions-api-v1 2.3.8+1802ada577 via fabric-api
- fabric-resource-loader-v0 0.11.10+1802ada577 via fabric-api
- fabric-screen-api-v1 2.0.8+1802ada577 via fabric-api
- fabric-screen-handler-api-v1 1.3.30+1802ada577 via fabric-api
- fabric-sound-api-v1 1.0.13+1802ada577 via fabric-api
- fabric-transfer-api-v1 3.3.5+8dd72ea377 via fabric-api
- fabric-transitive-access-wideners-v1 4.3.1+1802ada577 via fabric-api
- fabricloader 0.15.11
- fennecfox 1.0.0
- ferritecore 6.0.1
- fireworkminecart 1.1-1.20.1
- forgeconfigapiport 8.0.0
- forgeconfigscreens 8.0.2
- foxnap 0.1.2-3-dc2c4c37-1.20.0
- geckolib 4.4.7
- graphlib 1.4.0+1.20 via extended_drawers
- gravestones v1.15
- handcrafted 3.0.6
- hopobetterruinedportal 1.3.7
- hopobetterunderwaterruins 1.1.4
- icarae_origin 1.1.0-alpha.2
- icarus 2.9.1
- icommon 1.20.1 via icommon-bundle
- icommon-bundle bundle
- idwtialsimmoedm 0.3.1+1.20
- immediatelyfast 1.2.18+1.20.4
- indium 1.0.34+mc1.20.1
- inmis 2.7.2-1.20.1
- inventorymanagement 1.3.1
- io_determann_shadow-api-17 0.1.1 via config_toolkit
- io_github_douira_glsl-transformer 2.0.1 via iris
- io_leangen_geantyref_geantyref 1.3.13 via bobby
- io_netty_netty-codec-http 4.1.82 via computercraft
- io_netty_netty-codec-socks 4.1.82 via computercraft
- io_netty_netty-handler-proxy 4.1.82 via computercraft
- iris 1.7.2+mc1.20.1
- java 17
- kanos_config 0.4.1+1.14.4-1.19.4 via pehkui
- kirin 1.15.6+1.20.1 via presencefootsteps
- kiwi 11.6.2
- kmodlib-overlay 0.2.12+1.20 via graphlib
- krypton 0.2.3
- kuma_api 20.1.8 via balm-fabric
- lambdynlights 2.3.2+1.20.1
- lazydfu 0.1.3
- leashmod 1.0.6
- letmedespawn 1.2.1
- libipn 4.0.2
- libnetworkstack 0.10.0 via graphlib
- lithium 0.11.2
- lithostitched 1.1.6
- magicmirror 1.1.1
- me_xdrop_fuzzywuzzy 1.4.0 via nostalgic_tweaks
- memoryleakfix 1.1.5
- midnightlib 1.4.1 via cullleaves
- minecraft 1.20.1
- mixin-conflict-helper 1.2.0
- mixinextras 0.3.5 via fabricloader
- mixinsquared 0.1.1 via dynamictrim
- modelfix 1.15
- modernfix 5.18.1+mc1.20.1
- modmenu 7.2.2
- monolib 1.3.0
- moreculling 1.20.4-0.24.0
- mousetweaks 2.26
- mr_bft 2.0.0
- mr_ctov_croptopiacompat 2.0
- mr_origins_playerscale 3
- mr_trimmable_bows 1.0
- mr_trims_overhaul 2.3.4
- mru 0.4.4+1.20.1
- naturalist 4.0.3
- net_fabricmc_javapoet 0.1.0 via config_toolkit
- net_lenni0451_reflect 1.3.4 via immediatelyfast
- net_lostluma_battery 1.0.1 via dynamic_fps
- net_objecthunter_exp4j 0.4.8 via c2me
- no-resource-pack-warnings 1.3.0
- nochatreports 1.20.1-v2.2.2
- noindium 1.1.0+1.20 via extended_drawers
- nostalgic_tweaks 2.0.0-Beta-8.4.1
- notebook 3.1.0
- notenoughanimations 1.7.4
- omega-config 1.2.3-1.18.1 via inmis
- org_anarres_jcpp 1.4.14 via iris
- org_antlr_antlr4-runtime 4.13.1 via iris
- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
- org_javassist_javassist 3.29.2-GA via yungsapi
- org_jetbrains_kotlin_kotlin-reflect 2.0.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 2.0.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3 via fabric-language-kotlin
- org_quiltmc_parsers_gson 0.2.1 via yet_another_config_lib_v3
- org_quiltmc_parsers_json 0.2.1 via emitrades
- org_reflections_reflections 0.10.2 via betterdeserttemples
- org_spongepowered_configurate-core 4.1.2 via bobby
- org_spongepowered_configurate-hocon 4.1.2 via bobby
- org_threadly_threadly 7.0 via c2me
- origins 1.10.0
- origins-classes 1.7.0
- owo 0.11.2+1.20
- pehkui 3.8.3+1.14.4-1.21
- peripheralium 0.6.15
- peripheralworks 1.4.3
- playerabilitylib 1.8.0 via apoli
- polyeng 0.1.1-1.20.1
- polymer-registry-sync-manipulator 0.5.0+1.20 via vcinteraction
- polymorph 0.49.5+1.20.1
- presencefootsteps 1.9.4+1.20.1
- pride 1.2.0+1.19.4 via lambdynlights
- puzzlesaccessapi 8.0.7 via puzzleslib
- puzzleslib 8.1.21
- reach-entity-attributes 2.4.0 via origins
- reeses-sodium-options 1.7.2+mc1.20.1-build.101
- resourcefulconfig 2.1.2
- resourcefullib 2.1.25
- sleepwarp 2.2.0_rc1+1.20.1
- snowrealmagic 10.4.3
- sodium 0.5.11+mc1.20.1
- sodium-extra 0.5.4+mc1.20.1-build.115
- sound_physics_remastered 1.20.1-1.4.2
- sparsestructures 2.1.2
- spectrelib 0.13.15+1.20.1 via comforts
- spelunker 1.5.3-mc1.20
- spruceui 5.0.0+1.20 via enhancedblockentities
- spyglass_astronomy 1.0.10.1-mc1.20.1
- sspb 3.3.0
- starlight 1.1.2+fabric.dbc156f
- subterrestrial 2.2.0
- supermartijn642configlib 1.1.8+a
- supermartijn642corelib 1.1.17
- tbim 1.0.1
- team_reborn_energy 3.0.0 via ae2
- terrablender 3.0.1.7
- terralith 2.5.1
- tooltipfix 1.1.1-1.20
- touhoublessings 1.0.4
- touhouorigins 1.0.2
- trimmable_tools 1.0.6
- trinkets 3.7.2
- tuffbackport 0.1.0
- turtlematic 1.3.0
- tweed4_data 1.2.1+mc1.20-pre1 via spelunker
- tweed4_data_hjson 1.1.1+mc1.20-pre1 via spelunker
- vcinteraction 1.20.1-1.0.6
- villager-hats 1.6.2+1.20
- villagersplus 3.1
- visualizerbookshelf 2.0
- vmp 0.2.0+beta.7.102
- voicechat 1.20.1-2.5.18
- vulpine 1.0.1
- walkietalkie 1.3.0
- waterdripsound 1.19-0.3.2
- watut 1.20.1-1.1.1
- waveycapes 1.4.8
- waystones 14.1.4
- whydoesmyglasssoundlikethat 1.1.0
- wthit 8.13.2
- xaerominimap 24.2.0
- xaeroworldmap 1.38.8
- yet_another_config_lib_v3 3.5.0+1.20.1-fabric
- yosbr 0.1.2
- yungsapi 1.20-Fabric-4.0.5
```

## Game info
Minecraft Version: 1.20.1
Fabric Loader Version: 0.15.11

*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*

**Comment by astingraye** [comment]
I have the same issue, on 1.21.1

**Comment by TerraEgg** [comment]
Same error occurs with [pointblank](https://www.curseforge.com/minecraft/mc-mods/vics-point-blank).


(It is unlikely they are going to fix this, as it is more of a overlapping thing)
