### ISSUE TITLE
Crashing on SP startup 1.18.2

### ISSUE THREAD

**Issue by NevadaR** [BukkitFabric/bukkit4fabric#482]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/21/24, 11:58 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.CraftServer.getPluginManager()" because "org.bukkit.craftbukkit.CraftServer.INSTANCE" is null
	at net.minecraft.server.MinecraftServer.handler$zzb000$cardboard$onBeginCreateWorld(MinecraftServer.java:1927)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:420)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:330)
	at net.minecraft.class_1132.method_3823(class_1132.java:70)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

this is what it keeps throwing for the crash could use some help on getting it working thanks.

also im trying to get the movecraft plugin to work so maybe that might be causing a problem.

**Comment by NevadaR** [comment]
got a server running and it wont run the mod at all i feel like im doing something wrong
