### ISSUE TITLE
Server Crashes on start (MC 1.20.1)

### ISSUE THREAD

**Issue by Dark-Matter1** [BukkitFabric/bukkit4fabric#486]
When I try and start my server, using the fabric-server-mc.1.20.1-loader.0.16.9-launcher.1.0.1, the server outputs this error and crashes:
`[Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
	at io.izzel.arclight.api.Unsafe.ensureClassInitialized(Unsafe.java:85) ~[Cardboard-1.20.jar:?]
	at io.izzel.arclight.api.Unsafe.<clinit>(Unsafe.java:22) ~[Cardboard-1.20.jar:?]
	at org.bukkit.craftbukkit.util.CraftMagicNumbers.<clinit>(CraftMagicNumbers.java:156) ~[Cardboard-1.20.jar:?]
	at net.minecraft.class_3176.handler$zzb000$cardboard$init(class_3176.java:695) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:147) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1575) ~[?:?]`

then stops the server and outputs this last: 
`Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "$$5" is null
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:541) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:602) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:537) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:703) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1575) ~[?:?]`

For mods, I have Cardboard-1.20.jar, iCommon-Fabric-bundle.jar, and fabric-api-0.92.2+1.20.1.jar.
Happens with and without plugins installed.

I am not sure what is causing the issue so not sure how to reproduce.

**Comment by Jaec0b** [comment]
I get the same/similar crash on mc versions: 1.16.5, 1.18.2 1.20.1, 1.20.6, 1.21.1 with their respective latest versions of fabric, fabric api, cardboard, and icommon, i cannot get this mod working on my pc, i have no idea whats causing this crash but it could be hardware related because i know i got this mod working with some plugins a few years ago on my old pc on 1.16.5.
My old pc was a ryzen 5 2600, gtx 1650, 16gb ddr4 3000, sata ssd running windows 10, my current pc is a ryzen 7800x3d, rtx 4070 super, 32gb ddr5 6000, nvme ssd running latest drivers and windows 11. There is something that has changed from my old setup that makes this mod get this crash. I hope the devs fix this because i love this mod.

**Comment by vincent-alxr** [comment]
Hello it should be fixed now
