### ISSUE TITLE
Incompatible with Origins Mod - Mixin Crash

### ISSUE THREAD

**Issue by Timeken** [BukkitFabric/bukkit4fabric#49]
Put in Origins-1.16.3-0.4.1 and crashed

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2020-10-30 22:28
Description: Exception in server tick loop

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.class_3176.handler$zhd000$init(class_3176.java:698)
	at net.minecraft.class_3176.method_3823(class_3176.java:150)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.reach-entity-attributes.json:ServerPlayerInteractionManagerMixin] from phase [DEFAULT] in config [mixins.reach-entity-attributes.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("CONSTANT") on net/minecraft/class_3225::modifyReachDistance with priority 1000 cannot inject into net/minecraft/class_3225::method_14263(Lnet/minecraft/class_2338;Lnet/minecraft/class_2846$class_2847;Lnet/minecraft/class_2350;I)V merged by com.javazilla.bukkitfabric.mixin.MixinServerPlayerInteractionManager with priority 1000 [PREINJECT Applicator Phase -> mixins.reach-entity-attributes.json:ServerPlayerInteractionManagerMixin -> Prepare Injections ->  -> constant$znp000$modifyReachDistance(D)D -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_272, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 526920984 bytes (502 MB) / 1837629440 bytes (1752 MB) up to 3810525184 bytes (3634 MB)
	CPUs: 4
	JVM Flags: 0 total; 
	Fabric Mods: 
		adapaxels: AdaPaxels 1.0.3
		adventurez: AdventureZ 1.1.3
		antixray: SimpleAntiXray 1.0.0
		appleskin: AppleSkin 1.0.11
		autoconfig1u: Auto Config v1 Updated 3.3.1
		balance_of_exile: Balance of Exile 1.0.3
		bedspreads: Bedspreads 1.2.0-1.16.3
		blockus: Blockus 1.6.5
		bno: Basic Nether Ores 1.16.3-5.3.0-Fabric
		bukkitfabric: Bukkit for Fabric 1.16.3
		byg: BYG 1.0.14
		cardinal-components-base: Cardinal Components API (base) 2.7.1
		cardinal-components-chunk: Cardinal Components API (chunks) 2.6.0
		cardinal-components-entity: Cardinal Components API (entities) 2.7.1
		cardinal-components-world: Cardinal Components API (worlds) 2.6.0
		carpet: Carpet Mod in Fabric 1.4.12
		ce_foodstuffs: Common Expansion: Foodstuffs 1.1
		chainmail: Chainmail 0.5.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.2
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		croptopia: Croptopia 1.0.2-1.16.3-FABRIC
		cultivation: Cultivation 0.0.72
		curses: Curses 1.5.0
		dawn: Dawn API 1.4
		earthtojavamobs: Earth2Java 1.2.1+1.16.3
		emotecraft: Emotecraft 1.1.0
		expandedstorage: ExpandedStorage 5.6.30
		fabric: Fabric API 0.24.1+build.412-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.2+f8ac1db295
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5fa7
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.0+c270b09895
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.0+9f0fb4b895
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
		fabricloader: Fabric Loader 0.10.6+build.214
		fallflyinglib: FallFlyingLib 1.1.0
		fastfurnace: FastFurnace 2.3
		harvest_scythes: Harvest Scythes 1.0.3
		ice_boat_nerf: Ice Boat Nerf 1.0.2+MC1.16.2-1.16.3
		illuminations: Illuminations 1.2.2
		images: Images 0.3.1+1.16.3
		jankson: Jankson 3.0.0+j1.2.0
		jumploader: Jumploader 2.0.1
		libcd: LibCapableData 3.0.2+1.16.2
		library_of_exile: Library of Exile 1.0.6
		lithium: Lithium 0.5.6
		llamasteeds: Llama Steeds 2020.2.8
		minecraft: Minecraft 1.16.3
		minecraftcapes: MinecraftCapes Mod 10
		mooblooms: Mooblooms 1.3.2
		more_gems: More Gems 1.1.6
		nbtcrafting: NBT Crafting 2.0.0-rc.7+mc1.16.2-pre1
		netherroof: NetherRoofMod 1.0.0
		org_apache_httpcomponents_httpclient: httpclient 4.5.10
		org_apache_httpcomponents_httpcore: httpcore 4.4.12
		org_apache_httpcomponents_httpmime: httpmime 4.5.10
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		origins: Origins 0.4.1
		overworld_two: Overworld 2 1.0.3
		phosphor: Phosphor 0.6.0+build.7
		playerabilitylib: Pal 1.2.1
		randompatches: RandomPatches 1.16.1-0.0.0.5-fabric
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		rotten: FleshZ 1.2.2
		roughlyenoughitems: Roughly Enough Items 5.6.2
		roughlyenoughitems-api: REI (API) 5.6.2
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.6.2
		roughlyenoughitems-runtime: REI (Runtime) 5.6.2
		roughlyenoughresources: Roughly Enough Resources 2.1.2
		seasons: Fabric Seasons 0.3-BETA
		skinswapper: Minecraft Skin Change Mod 2.0.1
		spiceoffabric: Spice of Fabric 1.2.6+1.16.3
		suitablystackablestew: Suitably Stackable Stew 1.1.1
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		trade: Trade 1.1.0
		tweed: Tweed API 3.0.0-beta.15
		unforgivingvoid: Unforgiving Void 2.0.0
		wither_cage_fix: Mod Name 1.0.2+1.16.1-1.16.3
		xaerominimapfair: Xaero's Minimap Fair-Play 20.26.0
		xpstorage: XP Storage 1.1.1+1.16.3
	Data Packs: vanilla, fabric/fabric-tool-attribute-api-v1, fabric/xpstorage, fabric/rotten, fabric/seasons, fabric/spiceoffabric, fabric/images, fabric/bno, fabric/mooblooms, fabric/more_gems, fabric/expandedstorage, fabric/blockus (incompatible), fabric/bedspreads, fabric/adventurez, fabric/balance_of_exile (incompatible), fabric/earthtojavamobs, fabric/croptopia, fabric/cultivation, fabric/byg, fabric/ce_foodstuffs, fabric/adapaxels, fabric/libcd, fabric/origins
	Is Modded: Definitely; Server brand changed to 'Fabric,Bukkit'
	Type: Dedicated Server (map_server.txt)

**Comment by IsaiahPatton** [comment]
fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/26e4fd638a2b8fa41e07b9d493b4a0a1b9d46a8b

**Comment by ObsidianOS7** [comment]
New Bug with Origins

Beds in inv will default to the white bed after a while
so place quick after crafting
