### ISSUE TITLE
Incompatibility with the CarpetMod

### ISSUE THREAD

**Issue by Philogag** [BukkitFabric/bukkit4fabric#50]
This mod can not start up with the [fabric-carpet-mod](https://www.curseforge.com/minecraft/mc-mods/carpet).
This seems like a difficult problem to solve it so I don't hold out much hope for it. Because the carpet mod would change many game roles.

**Env:** 
+ Minecraft 1.16.3
+ Fabric 0.10.6+build.214
+ Fabric Api 0.25.0+build.415
+ [Fabric Carpet 1.16.3 1.4.12 v201001](https://www.curseforge.com/minecraft/mc-mods/carpet/files/3069670)
+ Bukkit4Fabric #120

**Crash Report**
[crash-2020-11-04_21.14.07-server.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5487984/crash-2020-11-04_21.14.07-server.txt)

**Console Out**
```
[21:13:45] [main/INFO]: Loading for game Minecraft 1.16.3
[21:13:46] [main/INFO]: [FabricLoader] Loading 43 mods: fabric-screen-handler-api-v1@1.1.0+8724984195, minecraft@1.16.3, fabric-renderer-api-v1@0.3.3+a4467d2a95, fabric-networking-blockentity-v0@0.2.5+b50ffc7b95, fabric-keybindings-v0@0.2.0+3fa9f7c595, fabric-command-api-v1@1.0.9+a4467d2a95, fabricloader@0.10.6+build.214, fabric-tool-attribute-api-v1@1.2.4+2b46237995, fabric-renderer-indigo@0.4.3+a4467d2a95, fabric-structure-api-v1@1.1.0+f8ac1db295, fabric-containers-v0@0.1.8+045df74f95, fabric-object-builder-api-v1@1.9.2+a89534ab95, fabric-item-api-v1@1.2.0+f8ac1db295, fabric-crash-report-info-v1@0.1.2+b7f9825d95, fabric-events-interaction-v0@0.4.1+f8ac1db295, bukkitfabric@1.16.2, fabric-game-rule-api-v1@1.0.3+a4467d2a95, fabric-api-base@0.2.0+9f0fb4b895, fabric-rendering-v0@1.1.1+f8ac1db295, fabric-rendering-v1@1.3.1+f8ac1db295, fabric-key-binding-api-v1@1.0.1+730711c695, fabric-rendering-data-attachment-v1@0.1.4+f8ac1db295, fabric-resource-loader-v0@0.3.1+facf3bbf95, fabric-textures-v0@1.0.5+a4467d2a95, fabric-content-registries-v0@0.1.9+059ea86695, fabric-tag-extensions-v0@1.0.3+ac8e8c5995, fabric-biome-api-v1@3.0.0+8367596d95, fabric-rendering-fluids-v1@0.1.12+f8ac1db295, fabric-registry-sync-v0@0.6.1+a4467d2a95, fabric-commands-v0@0.2.0+52d3083695, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8995, fabric-lifecycle-events-v1@1.2.0+74cc3b2095, fabric-mining-levels-v0@0.1.2+b764ce9995, fabric-renderer-registries-v1@2.2.0+f8ac1db295, fabric-loot-tables-v1@1.0.1+432ea18895, fabric-events-lifecycle-v0@0.2.0+16acbe5b95, fabric@0.25.0+build.415-1.16, carpet@1.4.12, fabric-particles-v1@0.2.2+fb0d9b0e95, fabric-models-v0@0.1.1+f8ac1db295, fabric-item-groups-v0@0.2.1+a4467d2a95, fabric-object-builders-v0@0.7.1+a4467d2a95, fabric-networking-v0@0.1.10+e00ecb5f95
[21:13:46] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/F:/Game/MC/Server/1.16.2test/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[21:13:46] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-v0.mixins.json:MixinEntityTracker and should be specified in value
[21:13:47] [main/WARN]: @Mixin target net/minecraft/class_1545$class_1546 is public in carpet.mixins.json:BlazeEntityShootFireballGoal_extremeMixin and should be specified in value
[21:13:55] [main/INFO]: Copyright ? 2020
[21:13:56] [main/INFO]: [STDERR]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/bukkitfabric/bukkit4fabric/compare/master...UNKNOWN
[21:13:56] [main/INFO]: [STDERR]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:13:56] [main/INFO]: [STDERR]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[21:13:56] [main/INFO]: [STDERR]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:13:56] [main/INFO]: [STDERR]:       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[21:13:56] [main/INFO]: [STDERR]:       at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
[21:13:56] [main/INFO]: [STDERR]:       at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
[21:13:56] [main/INFO]: [STDERR]:       at java.security.AccessController.doPrivileged(Native Method)
[21:13:56] [main/INFO]: [STDERR]:       at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
[21:13:56] [main/INFO]: [STDERR]:       at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
[21:13:56] [main/INFO]: [STDERR]:       at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[21:13:56] [main/INFO]: [STDERR]:       at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[21:13:56] [main/INFO]: [STDERR]:       at com.javazilla.bukkitfabric.command.VersionCommand.check(VersionCommand.java:195)
[21:13:56] [main/INFO]: [STDERR]:       at com.javazilla.bukkitfabric.BukkitFabricMod.onInitialize(BukkitFabricMod.java:22)
[21:13:56] [main/INFO]: [STDERR]:       at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
[21:13:56] [main/INFO]: [STDERR]:       at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
[21:13:56] [main/INFO]: [STDERR]:       at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32)
[21:13:56] [main/INFO]: [STDERR]:       at net.minecraft.server.Main.main(Main.java:93)
[21:13:56] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:13:56] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:13:56] [main/INFO]: [STDERR]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:13:56] [main/INFO]: [STDERR]:       at java.lang.reflect.Method.invoke(Method.java:498)
[21:13:56] [main/INFO]: [STDERR]:       at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
[21:13:56] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
[21:13:56] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27)
[21:13:56] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:13:56] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:13:56] [main/INFO]: [STDERR]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:13:56] [main/INFO]: [STDERR]:       at java.lang.reflect.Method.invoke(Method.java:498)
[21:13:56] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62)
[21:13:56] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)
[21:13:56] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)
[21:13:56] [main/INFO]: [STDERR]: Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/bukkitfabric/bukkit4fabric/compare/master...UNKNOWN
[21:13:56] [main/INFO]: [STDERR]:       at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
[21:13:56] [main/INFO]: [STDERR]:       at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[21:13:56] [main/INFO]: [STDERR]:       at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
[21:13:56] [main/INFO]: [STDERR]:       at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
[21:13:56] [main/INFO]: [STDERR]:       at com.javazilla.bukkitfabric.command.VersionCommand.check(VersionCommand.java:193)
[21:13:56] [main/INFO]: [STDERR]:       ... 19 more
[21:13:58] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[21:13:59] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:13:59] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:13:59] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:13:59] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:13:59] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:13:59] [main/INFO]: Reloading ResourceManager: Default, Fabric Tool Attribute API (v1)
[21:14:01] [Worker-Main-12/INFO]: Loaded 7 recipes
[21:14:01] [Worker-Main-12/INFO]: Loaded 927 advancements
[21:14:02] [main/INFO]: Applied 0 biome modifications to 0 of 79 new biomes in 2.714 ms
[21:14:03] [Server thread/INFO]: Starting minecraft server version 1.16.3
[21:14:03] [Server thread/INFO]: Loading properties
[21:14:03] [Server thread/INFO]: Default game type: SURVIVAL
[21:14:03] [Server thread/INFO]: Generating keypair
[21:14:03] [Server thread/INFO]: Starting Minecraft server on *:25565
[21:14:03] [Server thread/INFO]: Using default channel type
[21:14:07] [Server thread/INFO]:   ____          _     _     _  _
[21:14:07] [Server thread/INFO]:  |  _ \        | |   | |   (_)| |
[21:14:07] [Server thread/INFO]:  | |_) | _   _ | | __| | __ _ | |_
[21:14:07] [Server thread/INFO]:  |  _ < | | | || |/ /| |/ /| || __|
[21:14:07] [Server thread/INFO]:  | |_) || |_| ||   < |   < | || |_
[21:14:07] [Server thread/INFO]:  |____/  \__,_||_|\_\|_|\_\|_| \__|
[21:14:07] [Server thread/INFO]:
[21:14:07] [Server thread/FATAL]: Mixin apply failed carpet.mixins.json:ServerPlayerInteractionManager_cactusMixin -> net.minecraft.class_3225: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_3225::activateWithOptionalCactus with priority 1000 cannot inject into net/minecraft/class_3225::method_14262(Lnet/minecraft/class_3222;Lnet/minecraft/class_1937;Lnet/minecraft/class_1799;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_1269; merged by com.javazilla.bukkitfabric.mixin.MixinServerPlayerInteractionManager with priority 1000 [PREINJECT Applicator Phase -> carpet.mixins.json:ServerPlayerInteractionManager_cactusMixin -> Prepare Injections ->  -> redirect$zhe000$activateWithOptionalCactus(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_1269; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3225::activateWithOptionalCactus with priority 1000 cannot inject into net/minecraft/class_3225::method_14262(Lnet/minecraft/class_3222;Lnet/minecraft/class_1937;Lnet/minecraft/class_1799;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_1269; merged by com.javazilla.bukkitfabric.mixin.MixinServerPlayerInteractionManager with priority 1000 [PREINJECT Applicator Phase -> carpet.mixins.json:ServerPlayerInteractionManager_cactusMixin -> Prepare Injections ->  -> redirect$zhe000$activateWithOptionalCactus(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_1269; -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_221]
        at net.minecraft.class_3176.handler$zzd000$init(class_3176.java:675) ~[intermediary-server-1.16.3.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:150) ~[intermediary-server-1.16.3.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642) ~[intermediary-server-1.16.3.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server-1.16.3.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
[21:14:07] [Server thread/ERROR]: Encountered an unexpected exception
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_221]
        at net.minecraft.class_3176.handler$zzd000$init(class_3176.java:675) ~[intermediary-server-1.16.3.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:150) ~[intermediary-server-1.16.3.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642) ~[intermediary-server-1.16.3.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server-1.16.3.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [carpet.mixins.json:ServerPlayerInteractionManager_cactusMixin] from phase [DEFAULT] in config [carpet.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356) ~[fabric-server-launch.jar:?]
        ... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3225::activateWithOptionalCactus with priority 1000 cannot inject into net/minecraft/class_3225::method_14262(Lnet/minecraft/class_3222;Lnet/minecraft/class_1937;Lnet/minecraft/class_1799;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_1269; merged by com.javazilla.bukkitfabric.mixin.MixinServerPlayerInteractionManager with priority 1000 [PREINJECT Applicator Phase -> carpet.mixins.json:ServerPlayerInteractionManager_cactusMixin -> Prepare Injections ->  -> redirect$zhe000$activateWithOptionalCactus(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_1269; -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
        ... 11 more
[21:14:07] [Server thread/ERROR]: This crash report has been saved to: F:\Game\MC\Server\1.16.2test\.\crash-reports\crash-2020-11-04_21.14.07-server.txt
[21:14:07] [Server thread/INFO]: Stopping server
[21:14:07] [Server thread/INFO]: Saving worlds
[21:14:07] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: null
        at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:569) ~[intermediary-server-1.16.3.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:596) ~[intermediary-server-1.16.3.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:558) ~[intermediary-server-1.16.3.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:704) ~[intermediary-server-1.16.3.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server-1.16.3.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
[21:14:07] [Server thread/INFO]: Goodbye!
```

**Comment by QPCrummer** [comment]
I have the same problem as well. I swear, this mod and carpet mod sure do have many conflicts, which is weird because carpet mod is fairly simple.

**Comment by rafaeltab** [comment]
It actually started fine for me. However, when I set the tnt to not have any velocity it crashed and won't start again. Error: 
`Caused by: java.lang.ClassCastException: net.minecraft.class_1700 cannot be cast to com.javazilla.bukkitfabric.interfaces.IMixinInventory` (I do not have a full stack trace rn but there are probably not too many places where class_1700 is being casted to IMixinInvenotry)
