### ISSUE TITLE
Crash when world generation starts

### ISSUE THREAD

**Issue by Mario0051** [BukkitFabric/bukkit4fabric#8]
The crash is as follows, the only mods installed are this mod and Fabric API:
```
java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.class_3218.handler$zzk000$addToBukkit(class_3218.java:1531)
	at net.minecraft.class_3218.<init>(class_3218.java:208)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:365)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:332)
	at net.minecraft.class_1132.method_3823(class_1132.java:68)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by IsaiahPatton** [comment]
should be fixed now I believe.
