### ISSUE TITLE
Cannot replace blocks using WorldEdit (bukkit) 7.2.0 - B4F build 128

### ISSUE THREAD

**Issue by L0rdLogan** [BukkitFabric/bukkit4fabric#84]
[09:38:06] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.ExceptionInInitializerError: null
        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:268) ~[?:?]
        at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:143) ~[?:?]
        at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1009) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$4(PlatformCommandManager.java:249) ~[?:?]
        at java.util.Optional.map(Unknown Source) ~[?:1.8.0_251]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:248) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
        at java.util.Optional.flatMap(Unknown Source) ~[?:1.8.0_251]
        at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_251]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:1.8.0_251]
        at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
        at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
        at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
        at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:647) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_replace(RegionCommandsRegistration.java:450) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:494) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:375) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[Bukkit4Fabric-1.16.4.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:839) ~[Bukkit4Fabric-1.16.4.jar:?]
        at net.minecraft.class_3244.handler$zjk000$executeCommand(class_3244.java:1777) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_14370(class_3244.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12048(class_3244.java:1872) ~[intermediary-server.jar:?]
        at net.minecraft.class_2797.method_12115(class_2797.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2797.method_11054(class_2797.java:9) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[server.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitAdapter.asBlockType(BukkitAdapter.java:418) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_251]
        at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_251]
        at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getFromBukkitTag(BukkitBlockCategoryRegistry.java:37) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getCategorisedByName(BukkitBlockCategoryRegistry.java:48) ~[?:?]
        at com.sk89q.worldedit.world.registry.CategoryRegistry.getAll(CategoryRegistry.java:41) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockCategory.load(BlockCategory.java:46) ~[?:?]
        at com.sk89q.worldedit.registry.Category.getAll(Category.java:40) ~[?:?]
        at com.sk89q.worldedit.extent.reorder.MultiStageReorder.<clinit>(MultiStageReorder.java:58) ~[?:?]

**Comment by kristibektashi** [comment]
Lol i just opened the same issue (#83 )

**Comment by L0rdLogan** [comment]
> Lol i just opened the same issue (#83 )

Mine is a different error using world edit bukkit, not the digit version. Although there should be no difference really. The error is different

**Comment by kristibektashi** [comment]
Nvm then. But why is worldedit on the list of the known working plugins if it doesn't work?

**Comment by IsaiahPatton** [comment]
fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/26e4fd638a2b8fa41e07b9d493b4a0a1b9d46a8b
